import { SeoLocation, GlobalSeoSettings } from '../models/Seo';

export const defaultGlobalSeoSettings: GlobalSeoSettings = {
  id: 1,
  site_title: 'Gold Akingbade | Contemporary Fine Art & Fashion Photographer',
  meta_description: 'Fine art, high-fashion editorial, and portrait photography by Gold Akingbade. Documenting contemporary West African aesthetics, architectural stillness, and commissioned portraiture across Nigeria and internationally.',
  primary_keywords: 'fine art photographer Nigeria, fashion photographer Lagos, portrait photographer West Africa, editorial photography, documentary fine art',
  secondary_keywords: 'contemporary African photography, visual arts archive, Lagos fashion editorial, high-end portrait commissions, Idanre monoliths, Adire textile archive',
  canonical_url: 'https://goldakingbade.com',
  og_title: 'Gold Akingbade — Contemporary Visual Archive & Photography',
  og_description: 'Fine art, high-fashion editorial, and portraiture by Gold Akingbade. Monograph studies across contemporary West African landscapes.',
  og_image_url: '/storage/homepage/hero-preview.jpg',
  google_site_verification: '',
  robots_indexing: true,
  schema_type: 'PhotographyBusiness',
  created_at: new Date(),
  updated_at: new Date(),
};

// Seed dataset covering 36 Nigerian States + FCT Abuja (~74 strategic locations)
// Each location features authentic, unique, non-duplicated editorial narrative.
export const defaultNigerianLocations: SeoLocation[] = [
  // LAGOS STATE (4 key creative hubs)
  {
    id: 1,
    location_name: 'Ikeja',
    state: 'Lagos State',
    url_slug: 'photographer-in-ikeja',
    seo_title: 'Photographer in Ikeja, Lagos | Fine Art & Editorial Portraiture',
    meta_description: 'Commissioned fashion editorial, corporate portraiture, and fine art photography in Ikeja, Lagos. Architectural light, creative direction, and studio sessions.',
    primary_keyword: 'photographer in Ikeja',
    secondary_keywords: 'portrait photography Ikeja, fashion photographer Lagos Mainland, corporate portraits Ikeja GRA, creative direction Lagos',
    location_content: 'Working across the vibrant mainland landscape of Ikeja, from the colonial avenues of Ikeja GRA to dynamic industrial spaces. Commissions encompass executive portraiture, fashion lookbooks, and cultural editorial stories shaped by intense equatorial daylight and modern metropolitan energy.',
    services_offered: 'Editorial Fashion, High-End Portraiture, Lookbook Campaigns, Corporate Visual Direction',
    related_projects: [1, 4],
    og_title: 'Gold Akingbade — Editorial & Portrait Photography in Ikeja',
    og_description: 'Bespoke fashion editorial and portrait commissions in Ikeja, Lagos Mainland.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    location_name: 'Lekki',
    state: 'Lagos State',
    url_slug: 'photographer-in-lekki',
    seo_title: 'Photographer in Lekki, Lagos | Luxury Fashion & Fine Art Portrait Commissions',
    meta_description: 'High-fashion editorial, luxury portraiture, and coastal monograph photography in Lekki Peninsula, Lagos. Natural light studies and curated studio productions.',
    primary_keyword: 'photographer in Lekki',
    secondary_keywords: 'fashion photographer Lekki, luxury portrait photography Lekki Phase 1, coastal fine art photography, editorial lookbook Lekki',
    location_content: 'Lekki Peninsula offers a striking intersection of minimalist coastal architecture and open Atlantic horizon light. Photography commissions explore contemporary silhouettes, resort wear editorials, and intimate fine-art portraiture characterized by warm ocean tones and quiet elegance.',
    services_offered: 'Luxury Editorial, Architectural Portraits, Lookbook Direction, Fine Art Monographs',
    related_projects: [1, 5],
    og_title: 'Luxury Fashion & Editorial Photography in Lekki — Gold Akingbade',
    og_description: 'Contemporary fashion editorial and portrait commissions along the Lekki Peninsula.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 3,
    location_name: 'Victoria Island',
    state: 'Lagos State',
    url_slug: 'photographer-in-victoria-island',
    seo_title: 'Photographer in Victoria Island, Lagos | High-Fashion & Contemporary Art',
    meta_description: 'Contemporary fashion, gallery archive monographs, and private portrait sessions in Victoria Island (VI), Lagos. Sophisticated lighting and bespoke curation.',
    primary_keyword: 'photographer in Victoria Island',
    secondary_keywords: 'fashion photographer Victoria Island, art gallery documentation Lagos, executive portraits VI Lagos, luxury photography',
    location_content: 'At the heart of West African contemporary art and commerce, Victoria Island serves as a primary base for high-fashion campaigns, gallery monograph archives, and sophisticated editorial portraiture engaging with modernist architectural lines and atmospheric reflections.',
    services_offered: 'High-Fashion Campaigns, Gallery Portfolios, Executive Portraiture, Monograph Publications',
    related_projects: [1, 2],
    og_title: 'Contemporary Photography in Victoria Island — Gold Akingbade',
    og_description: 'High-fashion campaigns and fine art commissions in Victoria Island, Lagos.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 4,
    location_name: 'Yaba',
    state: 'Lagos State',
    url_slug: 'photographer-in-yaba',
    seo_title: 'Photographer in Yaba, Lagos | Creative Visual Arts & Editorial Stories',
    meta_description: 'Creative portraits, indie fashion lookbooks, and youth culture monographs in Yaba, Lagos. Authentic storytelling and raw, expressive aesthetics.',
    primary_keyword: 'photographer in Yaba',
    secondary_keywords: 'creative photographer Yaba, youth culture portraiture Lagos, indie fashion lookbook, documentary photography Yaba',
    location_content: 'Known as the pulse of Lagosian creative innovation and intellectual subcultures, Yaba provides an electric setting for experimental portraiture, avant-garde textile studies, and authentic cultural visual narratives.',
    services_offered: 'Creative Portraits, Streetwear Lookbooks, Cultural Documentary, Editorial Campaigns',
    related_projects: [2, 4],
    og_title: 'Creative Editorial Photography in Yaba — Gold Akingbade',
    og_description: 'Experimental and cultural visual stories captured across Yaba, Lagos.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // FCT ABUJA
  {
    id: 5,
    location_name: 'Maitama',
    state: 'FCT Abuja',
    url_slug: 'photographer-in-maitama',
    seo_title: 'Photographer in Maitama, Abuja | High-End Portraiture & Fine Art Commissions',
    meta_description: 'Bespoke fine art portraiture, diplomatic monographs, and couture fashion photography in Maitama, Abuja. Discretion, refined lighting, and timeless composition.',
    primary_keyword: 'photographer in Maitama',
    secondary_keywords: 'fine art photographer Abuja, portrait photographer Maitama, luxury couture photography Abuja, diplomatic portrait commissions',
    location_content: 'Maitama’s serene tree-lined boulevards and expansive modernist residences provide a tranquil atmosphere for distinguished fine-art portraiture and couture fashion commissions. Sessions emphasize subtle chiaroscuro, natural textures, and dignified aesthetic balance.',
    services_offered: 'Fine Art Portraiture, Couture Fashion, Diplomatic Archives, Private Commissions',
    related_projects: [1, 5],
    og_title: 'Fine Art Portraiture in Maitama, Abuja — Gold Akingbade',
    og_description: 'Discreet and refined portrait commissions in Maitama, Federal Capital Territory.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 6,
    location_name: 'Garki',
    state: 'FCT Abuja',
    url_slug: 'photographer-in-garki',
    seo_title: 'Photographer in Garki, Abuja | Editorial & Architectural Visual Archives',
    meta_description: 'Editorial fashion and architectural photography in Garki, Abuja. Dramatic stone topography, modernist institutional forms, and bespoke portrait commissions.',
    primary_keyword: 'photographer in Garki',
    secondary_keywords: 'architectural photographer Abuja, editorial portraiture Garki, fashion shoot Abuja Central, commercial visual direction',
    location_content: 'Interacting with Abuja’s monumental federal architecture and the dramatic surrounding hills, Garki offers a powerful canvas for high-contrast fashion storytelling and striking architectural compositions.',
    services_offered: 'Architectural Fashion, Editorial Sessions, Executive Portraits, Cultural Monographs',
    related_projects: [4, 5],
    og_title: 'Editorial & Architectural Photography in Garki, Abuja — Gold Akingbade',
    og_description: 'Monumental silhouettes and editorial commissions in Garki, Abuja.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // ONDO STATE
  {
    id: 7,
    location_name: 'Akure',
    state: 'Ondo State',
    url_slug: 'photographer-in-akure',
    seo_title: 'Photographer in Akure, Ondo State | Fine Art & Contemporary Editorial',
    meta_description: 'Fine art portraiture, cultural monographs, and fashion photography in Akure, Ondo State. Rich earth tones, natural rainforest lighting, and bespoke photo commissions.',
    primary_keyword: 'photographer in Akure',
    secondary_keywords: 'fine art photographer Akure, portrait studio Ondo State, cultural documentary Akure, fashion photographer Ondo',
    location_content: 'Set amidst lush rainforest canopies and rich laterite hills, Akure represents a vital creative hub for documenting authentic Yoruba heritage, traditional textile artisanship, and fine art portraits bathed in golden twilight.',
    services_offered: 'Fine Art Portraits, Cultural Monographs, Heritage Archives, Fashion Editorials',
    related_projects: [3, 2],
    og_title: 'Fine Art Photography in Akure, Ondo State — Gold Akingbade',
    og_description: 'Authentic cultural monographs and portrait commissions in Akure, Ondo State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 8,
    location_name: 'Idanre',
    state: 'Ondo State',
    url_slug: 'photographer-in-idanre',
    seo_title: 'Photographer in Idanre, Ondo State | Monolith Landscape & Fine Art Fashion',
    meta_description: 'Fine art fashion and landscape monograph photography on the historic granite monoliths of Idanre Hills. Ancient stone architecture and timeless light.',
    primary_keyword: 'photographer in Idanre',
    secondary_keywords: 'landscape photographer Idanre, Idanre hills fashion shoot, ancient monolith photography, fine art monograph Ondo',
    location_content: 'The ancient mountain settlement and 680 stone steps of Idanre provide an awe-inspiring natural amphitheater. Monograph projects harness dramatic cloud formations, thousand-year-old stone architecture, and rich organic clay tones.',
    services_offered: 'Landscape Fine Art, Monolith Fashion Editorials, Cultural Monographs, Archival Prints',
    related_projects: [3, 5],
    og_title: 'Monolith & Fine Art Photography in Idanre — Gold Akingbade',
    og_description: 'Dramatic fine art and high-fashion monographs staged on the ancient Idanre Hills.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // OYO STATE
  {
    id: 9,
    location_name: 'Ibadan',
    state: 'Oyo State',
    url_slug: 'photographer-in-ibadan',
    seo_title: 'Photographer in Ibadan, Oyo State | Heritage & Fine Art Portraiture',
    meta_description: 'Fine art portraiture, heritage textile archives, and fashion editorial in Ibadan, Oyo State. Rust-hued rooftops, tropical modernist light, and bespoke commissions.',
    primary_keyword: 'photographer in Ibadan',
    secondary_keywords: 'fine art photographer Ibadan, portrait photographer Bodija, Adire textile photography Ibadan, fashion photographer Oyo State',
    location_content: 'Ibadan’s sprawling landscape of oxidized zinc rooftops and modernist university architecture provides a deeply poetic backdrop. Visual projects focus on hand-dyed Adire textiles, scholarly elegance, and expressive chiaroscuro portraits.',
    services_offered: 'Textile Archives, Heritage Portraiture, Editorial Campaigns, Monograph Publications',
    related_projects: [2, 3],
    og_title: 'Heritage & Fine Art Photography in Ibadan — Gold Akingbade',
    og_description: 'Bespoke portraiture and textile archives captured across historic Ibadan.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 10,
    location_name: 'Ogbomoso',
    state: 'Oyo State',
    url_slug: 'photographer-in-ogbomoso',
    seo_title: 'Photographer in Ogbomoso, Oyo State | Cultural & Portrait Commissions',
    meta_description: 'Cultural portraiture, ceremonial archives, and landscape photography in Ogbomoso, Oyo State. Warm natural lighting and archival visual storytelling.',
    primary_keyword: 'photographer in Ogbomoso',
    secondary_keywords: 'portrait photographer Ogbomoso, cultural documentary Oyo State, ceremonial photography, fine art prints',
    location_content: 'Documenting the deep royal lineages, traditional courtyards, and savannah light of Ogbomoso. Commissions focus on timeless family archives, cultural ceremonies, and fine art portraits honoring ancestral roots.',
    services_offered: 'Ceremonial Archives, Cultural Portraits, Family Monographs, Fine Art Commissions',
    related_projects: [2, 4],
    og_title: 'Cultural Photography in Ogbomoso — Gold Akingbade',
    og_description: 'Authentic cultural archives and portrait sessions in Ogbomoso, Oyo State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.75,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // RIVERS STATE
  {
    id: 11,
    location_name: 'Port Harcourt',
    state: 'Rivers State',
    url_slug: 'photographer-in-port-harcourt',
    seo_title: 'Photographer in Port Harcourt, Rivers State | Contemporary Editorial & Portraits',
    meta_description: 'Fine art portraiture, luxury fashion editorial, and coastal Niger Delta narratives in Port Harcourt, Rivers State. Expert lighting and bespoke visual direction.',
    primary_keyword: 'photographer in Port Harcourt',
    secondary_keywords: 'fashion photographer Port Harcourt, portrait photographer GRA Port Harcourt, Niger Delta fine art photography, luxury campaigns',
    location_content: 'Port Harcourt’s lush garden avenues and dynamic waterfronts create an atmospheric setting for contemporary fashion editorials and high-profile executive portraiture exploring coastal light and sophisticated modern style.',
    services_offered: 'High-Fashion Editorial, Executive Portraits, Maritime Visual Monographs, Luxury Campaigns',
    related_projects: [1, 5],
    og_title: 'Contemporary Photography in Port Harcourt — Gold Akingbade',
    og_description: 'Luxury editorial and portrait commissions in Port Harcourt, Rivers State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.9,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 12,
    location_name: 'Bonny Island',
    state: 'Rivers State',
    url_slug: 'photographer-in-bonny-island',
    seo_title: 'Photographer in Bonny Island, Rivers State | Coastal Fine Art & Industrial Monograph',
    meta_description: 'Coastal fine art photography, maritime monograph stories, and portraiture on historic Bonny Island, Rivers State. Oceanic horizons and timeless visual archives.',
    primary_keyword: 'photographer in Bonny Island',
    secondary_keywords: 'fine art photographer Bonny Island, coastal monograph Rivers State, maritime editorial photography, historic island portraits',
    location_content: 'Rich in trade history and surrounded by the open Atlantic, Bonny Island offers breathtaking coastal sceneries and clean maritime horizons ideal for environmental portraiture and industrial fine-art monographs.',
    services_offered: 'Maritime Monographs, Coastal Portraiture, Industrial Fine Art, Heritage Documentation',
    related_projects: [5, 1],
    og_title: 'Coastal Fine Art Photography in Bonny Island — Gold Akingbade',
    og_description: 'Fine art monographs and coastal portrait commissions on Bonny Island.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // EDO STATE
  {
    id: 13,
    location_name: 'Benin City',
    state: 'Edo State',
    url_slug: 'photographer-in-benin-city',
    seo_title: 'Photographer in Benin City, Edo State | Royal Heritage & Fine Art Bronze Archives',
    meta_description: 'Fine art photography, royal ceremonial archives, and contemporary portraiture in Benin City, Edo State. Documenting the legendary artisan guilds and ancient kingdom legacy.',
    primary_keyword: 'photographer in Benin City',
    secondary_keywords: 'fine art photographer Benin City, bronze casting documentation Edo, royal coral portraiture, cultural photographer Nigeria',
    location_content: 'Home to the storied brass and bronze guilds of Igun Street and the ancient Benin Kingdom, visual commissions in Benin City embrace royal coral regalia, red mud palace architecture, and timeless sculptural silhouettes.',
    services_offered: 'Royal Cultural Archives, Artisanal Guild Monographs, Fine Art Portraits, Coral Regalia Editorial',
    related_projects: [2, 4],
    og_title: 'Royal Heritage & Fine Art Photography in Benin City — Gold Akingbade',
    og_description: 'Documenting centuries of craft, royal regalia, and fine art in Benin City, Edo State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // ENUGU STATE
  {
    id: 14,
    location_name: 'Enugu',
    state: 'Enugu State',
    url_slug: 'photographer-in-enugu',
    seo_title: 'Photographer in Enugu | Fine Art Coal City Landscapes & Editorial Portraits',
    meta_description: 'Fine art portraiture, fashion editorial, and pine forest monographs in Enugu, Coal City. Wavy hills, historical colliery architecture, and golden light.',
    primary_keyword: 'photographer in Enugu',
    secondary_keywords: 'fine art photographer Enugu, portrait photographer Independence Layout, Milliken Hill fashion shoot, fashion photographer Coal City',
    location_content: 'Enugu’s rolling hills, pine reserves, and modernist coal-mining legacy offer a rich topography for cinematic editorial shoots, fine-art portraiture, and high-fashion lookbooks inspired by lush eastern highlands.',
    services_offered: 'Cinematic Fashion, Highland Portraits, Historical Monographs, Creative Lookbooks',
    related_projects: [3, 5],
    og_title: 'Fine Art Photography in Enugu — Gold Akingbade',
    og_description: 'Highland landscapes and bespoke portrait commissions in Enugu, Coal City.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // CROSS RIVER STATE
  {
    id: 15,
    location_name: 'Calabar',
    state: 'Cross River State',
    url_slug: 'photographer-in-calabar',
    seo_title: 'Photographer in Calabar, Cross River | Heritage Monograph & Fine Art',
    meta_description: 'Fine art portraiture, carnival fashion editorial, and rainforest monographs in Calabar, Cross River State. Serene botanical light and colonial historical architecture.',
    primary_keyword: 'photographer in Calabar',
    secondary_keywords: 'fine art photographer Calabar, portrait photographer Cross River, carnival costume photography, botanical monographs',
    location_content: 'From the tranquil shores of the Calabar River to historic Victorian-era stone estates, Calabar offers an exceptionally gentle natural light ideal for botanical fashion editorials, bespoke portraits, and festival art documentation.',
    services_offered: 'Botanical Fashion, Festival Regalia Archives, Heritage Portraits, Fine Art Prints',
    related_projects: [2, 3],
    og_title: 'Heritage & Fine Art Photography in Calabar — Gold Akingbade',
    og_description: 'Fine art monographs and portrait commissions in historic Calabar, Cross River State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // KANO STATE
  {
    id: 16,
    location_name: 'Kano',
    state: 'Kano State',
    url_slug: 'photographer-in-kano',
    seo_title: 'Photographer in Kano | Ancient Dye Pits & Sahelian Fine Art Monographs',
    meta_description: 'Sahelian fine art photography, Kofar Mata indigo dye pit archives, and royal Durbar equestrian portraiture in historic Kano City. Ancient mud-brick textures and desert light.',
    primary_keyword: 'photographer in Kano',
    secondary_keywords: 'fine art photographer Kano, Kofar Mata dye pits photography, Durbar festival photographer, Sahelian fashion editorial',
    location_content: 'The 500-year-old Kofar Mata indigo dye pits and the majestic mud-brick architecture of the ancient Kano city walls form an extraordinary visual theatre for textile heritage archives, equestrian Durbar monographs, and haute-couture Sahelian fashion.',
    services_offered: 'Textile Heritage Archives, Sahelian Fashion, Durbar Equestrian Monographs, Architectural Chiaroscuro',
    related_projects: [2, 5],
    og_title: 'Ancient Dye Pits & Fine Art Photography in Kano — Gold Akingbade',
    og_description: 'Documenting centuries of natural indigo artisanship and royal heritage in Kano City.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.9,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // KADUNA STATE
  {
    id: 17,
    location_name: 'Kaduna',
    state: 'Kaduna State',
    url_slug: 'photographer-in-kaduna',
    seo_title: 'Photographer in Kaduna | Modernist Northern Heritage & Portrait Commissions',
    meta_description: 'Fine art portraiture, equestrian polo monographs, and architectural photography in Kaduna. Crisp northern savanna sunlight and classic mid-century lines.',
    primary_keyword: 'photographer in Kaduna',
    secondary_keywords: 'portrait photographer Kaduna, polo sports photographer Kaduna, architectural monographs Northern Nigeria, fine art studio',
    location_content: 'Kaduna’s distinct mid-century modernist buildings, broad Jacaranda avenues, and rich equestrian culture provide a distinguished setting for executive portraiture, sporting monographs, and minimalist architectural fashion.',
    services_offered: 'Equestrian Monographs, Executive Portraits, Architectural Fashion, Fine Art Commissions',
    related_projects: [4, 5],
    og_title: 'Fine Art & Portrait Photography in Kaduna — Gold Akingbade',
    og_description: 'Equestrian archives and architectural portraiture in Kaduna, Northern Nigeria.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // OGUN STATE
  {
    id: 18,
    location_name: 'Abeokuta',
    state: 'Ogun State',
    url_slug: 'photographer-in-abeokuta',
    seo_title: 'Photographer in Abeokuta, Ogun State | Olumo Rock & Adire Textile Archives',
    meta_description: 'Fine art photography, historic Olumo Rock monographs, and Kemta Adire textile documentation in Abeokuta, Ogun State. Ancient granite forms and authentic craftsmanship.',
    primary_keyword: 'photographer in Abeokuta',
    secondary_keywords: 'fine art photographer Abeokuta, Olumo rock fashion shoot, Kemta Adire market photography, Ogun state portraits',
    location_content: 'The monumental granite summit of Olumo Rock and the historic Adire markets of Itoku offer a rich dialogue between ancient stone geology and living indigo textile heritage. Visual projects emphasize raw earth pigments and striking organic light.',
    services_offered: 'Adire Craft Monographs, Granite Landscape Editorials, Heritage Portraiture, Cultural Archives',
    related_projects: [2, 3],
    og_title: 'Olumo Rock & Adire Photography in Abeokuta — Gold Akingbade',
    og_description: 'Textile heritage and granite monolith archives captured in Abeokuta, Ogun State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // DELTA STATE
  {
    id: 19,
    location_name: 'Asaba',
    state: 'Delta State',
    url_slug: 'photographer-in-asaba',
    seo_title: 'Photographer in Asaba, Delta State | River Niger Fine Art & Cinematic Portraits',
    meta_description: 'Cinematic portraiture, River Niger shoreline photography, and high-fashion editorial in Asaba, Delta State. Atmospheric water reflections and contemporary visual storytelling.',
    primary_keyword: 'photographer in Asaba',
    secondary_keywords: 'cinematic photographer Asaba, River Niger photo shoot, portrait photographer Delta State, film lookbook Asaba',
    location_content: 'Positioned on the banks of the majestic River Niger, Asaba provides a luminous setting where shimmering water reflections and humid tropical twilight create evocative atmospheres for cinematic fashion and private portrait sessions.',
    services_offered: 'Cinematic Fashion, Waterfront Monographs, Fine Art Portraits, Lookbook Production',
    related_projects: [1, 3],
    og_title: 'Cinematic & Fine Art Photography in Asaba — Gold Akingbade',
    og_description: 'River Niger shoreline monographs and fine art portrait sessions in Asaba, Delta State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 20,
    location_name: 'Warri',
    state: 'Delta State',
    url_slug: 'photographer-in-warri',
    seo_title: 'Photographer in Warri, Delta State | Coastal Energy & Expressive Portraiture',
    meta_description: 'Expressive fine art portraiture, cultural monographs, and contemporary fashion photography in Warri, Delta State. Bold lighting and vibrant coastal Niger Delta character.',
    primary_keyword: 'photographer in Warri',
    secondary_keywords: 'portrait photographer Warri, Delta State fashion photographer, cultural documentary Warri, editorial photography',
    location_content: 'Capturing the proud cultural heritage of the Itsekiri, Urhobo, and Ijaw traditions against the industrial and maritime textures of Warri. Visual studies celebrate elaborate ceremonial silks, coral crowns, and bold natural confidence.',
    services_offered: 'Cultural Ceremonial Archives, Expressive Portraits, Maritime Fashion, Monograph Prints',
    related_projects: [2, 4],
    og_title: 'Expressive Cultural Photography in Warri — Gold Akingbade',
    og_description: 'Documenting Niger Delta coastal culture, ceremonial silks, and fine art in Warri.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // AKWA IBOM STATE
  {
    id: 21,
    location_name: 'Uyo',
    state: 'Akwa Ibom State',
    url_slug: 'photographer-in-uyo',
    seo_title: 'Photographer in Uyo, Akwa Ibom | Modernist Architecture & Fine Art Portraits',
    meta_description: 'Contemporary fashion editorial, clean architectural photography, and fine art portraiture in Uyo, Akwa Ibom State. Lush tropical greenery and serene visual harmony.',
    primary_keyword: 'photographer in Uyo',
    secondary_keywords: 'fine art photographer Uyo, fashion photographer Akwa Ibom, architectural portraits Uyo, luxury portrait commissions',
    location_content: 'Uyo’s immaculately landscaped boulevards, pristine modernist sports stadiums, and tropical rainforest reserves offer an inspiring clarity of light for high-fashion lookbooks and bespoke fine-art portraits.',
    services_offered: 'High-Fashion Editorials, Architectural Portraits, Cultural Monograph Series, Studio Sessions',
    related_projects: [1, 5],
    og_title: 'Fine Art & Editorial Photography in Uyo — Gold Akingbade',
    og_description: 'Pristine architectural light and bespoke portrait commissions in Uyo, Akwa Ibom.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // PLATEAU STATE
  {
    id: 22,
    location_name: 'Jos',
    state: 'Plateau State',
    url_slug: 'photographer-in-jos',
    seo_title: 'Photographer in Jos, Plateau State | High Altitude Light & Granite Monograph',
    meta_description: 'Fine art landscape photography, highland fashion editorial, and portraiture in Jos, Plateau State. Cool mountain mist, volcanic rock formations, and clear high-altitude light.',
    primary_keyword: 'photographer in Jos',
    secondary_keywords: 'fine art photographer Jos, Plateau State landscape photography, highland fashion shoot, volcanic rock monographs',
    location_content: 'Perched over 1,200 meters above sea level, Jos enjoys crisp mountain air, volcanic crater lakes, and dramatic rock formations that diffuse sunlight into a cool, Nordic-like softness unmatched anywhere in West Africa.',
    services_offered: 'Highland Fine Art, Monolith Fashion Editorials, Mountain Landscape Monographs, Archival Prints',
    related_projects: [3, 5],
    og_title: 'High Altitude Fine Art Photography in Jos — Gold Akingbade',
    og_description: 'Cool mountain mist and granite landscape monographs captured in Jos, Plateau State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // OSUN STATE
  {
    id: 23,
    location_name: 'Osogbo',
    state: 'Osun State',
    url_slug: 'photographer-in-osogbo',
    seo_title: 'Photographer in Osogbo, Osun State | Sacred Grove Fine Art & Susanne Wenger Legacy',
    meta_description: 'Sacred grove monographs, fine art documentary, and cultural portraiture in Osogbo, Osun State. UNESCO heritage forests and sculptural New Sacred Art architecture.',
    primary_keyword: 'photographer in Osogbo',
    secondary_keywords: 'fine art photographer Osogbo, Osun sacred grove photo series, cultural documentary Osun state, Susanne Wenger architecture photography',
    location_content: 'The UNESCO-inscribed Osun-Osogbo Sacred Grove, dense with ancient hardwood trees and mystical cement sculptures, provides a sacred sanctum for fine-art monographs exploring spiritual stillness, traditional brass deities, and organic light.',
    services_offered: 'Sacred Heritage Monographs, Fine Art Documentary, Cultural Portraiture, Museum Prints',
    related_projects: [2, 5],
    og_title: 'Sacred Grove & Fine Art Photography in Osogbo — Gold Akingbade',
    og_description: 'Fine art monographs documenting sacred sculptural architecture and cultural memory in Osogbo.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 24,
    location_name: 'Ile-Ife',
    state: 'Osun State',
    url_slug: 'photographer-in-ile-ife',
    seo_title: 'Photographer in Ile-Ife, Osun State | Ancient Yoruba Antiquities & Royal Regalia',
    meta_description: 'Fine art portraiture, archaeological monographs, and royal ceremonial photography in historic Ile-Ife, Osun State. Documenting the cradle of ancient Yoruba civilization.',
    primary_keyword: 'photographer in Ile-Ife',
    secondary_keywords: 'fine art photographer Ile-Ife, Yoruba antiquity photography, royal regalia portraiture, archaeological monograph Osun',
    location_content: 'Revered as the ancient source of Yoruba civilisation and world-renowned terracotta and bronze masterworks, Ile-Ife is a profound setting for ceremonial portraiture, ancient court regalia, and museum-grade fine art monographs.',
    services_offered: 'Royal Antiquity Archives, Ceremonial Portraiture, Terracotta Fine Art Monographs, Heritage Documentation',
    related_projects: [2, 4],
    og_title: 'Ancient Antiquities & Royal Photography in Ile-Ife — Gold Akingbade',
    og_description: 'Monographs honoring ancient bronze, terracotta, and royal heritage in historic Ile-Ife.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // KWARA STATE
  {
    id: 25,
    location_name: 'Ilorin',
    state: 'Kwara State',
    url_slug: 'photographer-in-ilorin',
    seo_title: 'Photographer in Ilorin, Kwara State | Aso-Oke Weaving Heritage & Fine Art',
    meta_description: 'Fine art textile monographs, Aso-Oke handloom archives, and traditional pottery photography in Ilorin, Kwara State. Sahelian transition light and artisan heritage.',
    primary_keyword: 'photographer in Ilorin',
    secondary_keywords: 'Aso-Oke textile photographer Ilorin, Dada pottery documentation, fine art photographer Kwara State, cultural portraits Ilorin',
    location_content: 'At the historical crossroads of northern and southern cultures, Ilorin’s ancient Dada pottery pits and master Aso-Oke handloom quarters provide an unparalleled backdrop for tactile textile fashion editorials and artisanal craft monographs.',
    services_offered: 'Textile Weaving Archives, Artisanal Pottery Monographs, Fashion Editorials, Fine Art Prints',
    related_projects: [4, 2],
    og_title: 'Aso-Oke Weaving & Fine Art Photography in Ilorin — Gold Akingbade',
    og_description: 'Capturing centuries of master textile weaving and artisanal craft in Ilorin, Kwara State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // ANAMBRA STATE
  {
    id: 26,
    location_name: 'Awka',
    state: 'Anambra State',
    url_slug: 'photographer-in-awka',
    seo_title: 'Photographer in Awka, Anambra State | Blacksmithing Heritage & Fine Art Portraits',
    meta_description: 'Fine art portraiture, blacksmithing guild archives, and cultural monographs in Awka, Anambra State. Metalcraft textures, warm firelight, and bespoke visual art.',
    primary_keyword: 'photographer in Awka',
    secondary_keywords: 'fine art photographer Awka, blacksmith guild photography Anambra, cultural portraiture Awka, editorial photo commissions',
    location_content: 'Awka’s renowned metalworking heritage and ancient blacksmith guilds offer a dramatic study in fire, hammered iron, and raw artisanal grit, paired with bespoke contemporary Igbo cultural portraiture.',
    services_offered: 'Metalcraft Guild Archives, Cultural Monographs, Executive Portraits, Fine Art Commissions',
    related_projects: [4, 5],
    og_title: 'Metalcraft & Cultural Photography in Awka — Gold Akingbade',
    og_description: 'Documenting centuries of iron forge craft and cultural portraiture in Awka, Anambra State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 27,
    location_name: 'Onitsha',
    state: 'Anambra State',
    url_slug: 'photographer-in-onitsha',
    seo_title: 'Photographer in Onitsha, Anambra State | River Niger Commerce & Monumental Monograph',
    meta_description: 'Monumental architecture, River Niger bridge photography, and dynamic commercial monographs in Onitsha, Anambra State. River twilight and trade heritage.',
    primary_keyword: 'photographer in Onitsha',
    secondary_keywords: 'River Niger bridge photography Onitsha, commercial monograph Anambra, architectural photographer Onitsha, cultural archives',
    location_content: 'Framed by the monumental River Niger Bridge and the bustling pulse of West Africa’s largest trade exchange, Onitsha visual projects capture dramatic metallic reflections and vibrant human movement under sweeping sunset skies.',
    services_offered: 'Architectural Bridge Monographs, Commercial Visual Direction, Editorial Portraits, Fine Art Prints',
    related_projects: [1, 5],
    og_title: 'River Niger & Architectural Photography in Onitsha — Gold Akingbade',
    og_description: 'Monumental river architecture and dynamic visual stories captured in Onitsha.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // IMO STATE
  {
    id: 28,
    location_name: 'Owerri',
    state: 'Imo State',
    url_slug: 'photographer-in-owerri',
    seo_title: 'Photographer in Owerri, Imo State | Contemporary Lifestyle & Fine Art Portraiture',
    meta_description: 'High-end portrait commissions, hospitality monographs, and lifestyle fashion photography in Owerri, Imo State. Elegant warm lighting and bespoke direction.',
    primary_keyword: 'photographer in Owerri',
    secondary_keywords: 'portrait photographer Owerri, fashion photographer Imo State, luxury lifestyle photography Owerri, editorial commissions',
    location_content: 'Owerri’s relaxed, cosmopolitan hospitality culture and lush tropical palm greenery provide a graceful canvas for refined lifestyle editorials, couture fashion lookbooks, and celebratory family archives.',
    services_offered: 'Lifestyle Fashion, Couture Lookbooks, Private Family Monographs, Fine Art Portraits',
    related_projects: [1, 3],
    og_title: 'Fine Art & Lifestyle Photography in Owerri — Gold Akingbade',
    og_description: 'Refined lifestyle editorials and bespoke portrait commissions in Owerri, Imo State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // EKITI STATE
  {
    id: 29,
    location_name: 'Ado-Ekiti',
    state: 'Ekiti State',
    url_slug: 'photographer-in-ado-ekiti',
    seo_title: 'Photographer in Ado-Ekiti, Ekiti State | Mountain Mist & Fine Art Portraiture',
    meta_description: 'Fine art portraiture, rocky highland landscape monographs, and cultural archives in Ado-Ekiti, Ekiti State. Pristine natural light and mountainous tranquility.',
    primary_keyword: 'photographer in Ado-Ekiti',
    secondary_keywords: 'fine art photographer Ado Ekiti, Ekiti state landscape photography, Ikogosi warm spring editorial, mountain portraits',
    location_content: 'Nestled between dramatic granite ridges and ancient forest canopies, Ado-Ekiti is an ideal sanctuary for contemplative fine art portraiture, warm spring landscape studies, and organic fashion monographs.',
    services_offered: 'Mountain Landscape Monographs, Highland Fashion, Cultural Portraits, Archival Prints',
    related_projects: [3, 5],
    og_title: 'Mountain & Fine Art Photography in Ado-Ekiti — Gold Akingbade',
    og_description: 'Granite highland landscapes and fine art portrait sessions in Ado-Ekiti, Ekiti State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // SOKOTO STATE
  {
    id: 30,
    location_name: 'Sokoto',
    state: 'Sokoto State',
    url_slug: 'photographer-in-sokoto',
    seo_title: 'Photographer in Sokoto | Caliphate Antiquities & Sahelian Chiaroscuro',
    meta_description: 'Fine art photography, Sultan Palace royal archives, and Sahelian leathercraft documentation in historic Sokoto City. Golden desert twilight and Islamic architecture.',
    primary_keyword: 'photographer in Sokoto',
    secondary_keywords: 'fine art photographer Sokoto, Sultan palace photography, Sahelian leathercraft documentation, desert light portraiture',
    location_content: 'The historic seat of the Sokoto Caliphate boasts timeless mud architecture, world-renowned goatskin and leather artisanal quarters, and breathtaking amber desert light that renders subjects in striking, reverent chiaroscuro.',
    services_offered: 'Caliphate Royal Archives, Leather Artisanship Monographs, Sahelian Portraits, Architectural Studies',
    related_projects: [2, 5],
    og_title: 'Caliphate Heritage & Fine Art Photography in Sokoto — Gold Akingbade',
    og_description: 'Documenting centuries of leather artisanal craft and Islamic architectural stillness in Sokoto.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.85,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // BORNO STATE
  {
    id: 31,
    location_name: 'Maiduguri',
    state: 'Borno State',
    url_slug: 'photographer-in-maiduguri',
    seo_title: 'Photographer in Maiduguri, Borno | Kanem-Borno Cultural Monograph & Fine Art',
    meta_description: 'Sahelian cultural archives, Kanuri ceremonial regalia, and fine art documentary in Maiduguri, Borno State. Thousand-year heritage and sweeping desert horizons.',
    primary_keyword: 'photographer in Maiduguri',
    secondary_keywords: 'cultural photographer Maiduguri, Kanuri traditional regalia, Sahelian landscape photography, Borno fine art',
    location_content: 'Drawing upon the thousand-year heritage of the Kanem-Borno Empire, visual projects in Maiduguri document exquisite Kanuri ceremonial embroidery, desert clay architecture, and the resilient cultural spirit of the Chad Basin.',
    services_offered: 'Sahelian Cultural Archives, Kanuri Regalia Monographs, Desert Landscapes, Fine Art Prints',
    related_projects: [2, 4],
    og_title: 'Sahelian Heritage Photography in Maiduguri — Gold Akingbade',
    og_description: 'Documenting Kanuri cultural heritage and desert horizon light in Maiduguri, Borno State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.75,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // BENUE STATE
  {
    id: 32,
    location_name: 'Makurdi',
    state: 'Benue State',
    url_slug: 'photographer-in-makurdi',
    seo_title: 'Photographer in Makurdi, Benue State | River Benue Shorelines & Tiv Cultural Textiles',
    meta_description: 'Fine art photography, anger traditional textile documentation, and River Benue landscape monographs in Makurdi. River twilight and agrarian cultural archives.',
    primary_keyword: 'photographer in Makurdi',
    secondary_keywords: 'fine art photographer Makurdi, Tiv anger cloth photography, River Benue photo shoot, cultural portraits Benue',
    location_content: 'Overlooking the broad sweeps of the River Benue, Makurdi offers a serene visual dialogue between luminous river reflections and the striking black-and-white geometric stripes of traditional Tiv Anger handwoven textiles.',
    services_offered: 'Textile Weaving Monographs, River Landscape Series, Cultural Portraiture, Archival Prints',
    related_projects: [4, 5],
    og_title: 'River Benue & Textile Photography in Makurdi — Gold Akingbade',
    og_description: 'Documenting Tiv handloom textiles and River Benue landscapes in Makurdi, Benue State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // NIGER STATE
  {
    id: 33,
    location_name: 'Minna',
    state: 'Niger State',
    url_slug: 'photographer-in-minna',
    seo_title: 'Photographer in Minna, Niger State | Zuma Rock & Gurara Waterfalls Monographs',
    meta_description: 'Monumental rock landscape photography, Gurara Waterfalls fine art, and portraiture in Minna, Niger State. Dramatic natural wonders and ancient pottery traditions.',
    primary_keyword: 'photographer in Minna',
    secondary_keywords: 'Zuma rock photographer, Gurara waterfalls photo shoot, landscape fine art Niger State, portrait studio Minna',
    location_content: 'Surrounded by monumental inselbergs like Zuma Rock and the rushing waters of Gurara Falls, Minna provides an extraordinary geological stage for high-contrast fashion monographs and contemplative fine-art landscape studies.',
    services_offered: 'Monumental Landscape Fine Art, Waterfall Fashion Series, Nupe Pottery Archives, Private Portraits',
    related_projects: [3, 5],
    og_title: 'Monumental Landscape Photography in Minna — Gold Akingbade',
    og_description: 'Zuma Rock and Gurara Waterfalls fine art monographs captured in Niger State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 34,
    location_name: 'Bida',
    state: 'Niger State',
    url_slug: 'photographer-in-bida',
    seo_title: 'Photographer in Bida, Niger State | Nupe Brass & Glass Artisans Archive',
    meta_description: 'Fine art documentary, Nupe glass-making guild photography, and brass casting monographs in historic Bida, Niger State. Molten glass firelight and ancient metalcraft.',
    primary_keyword: 'photographer in Bida',
    secondary_keywords: 'Nupe glassmakers photography Bida, brass casting guild Niger State, fine art documentary Bida, artisanal crafts Nigeria',
    location_content: 'Bida is world-famous for its ancient guild of Masaga glassmakers and Nupe brass casters who forge glowing molten glass and ornate brass vessels over charcoal embers. Monograph series celebrate the raw visual drama of fire, ash, and incandescent craftsmanship.',
    services_offered: 'Glassmaking Guild Archives, Brass Foundry Monographs, Artisanal Heritage Documentation, Fine Art Prints',
    related_projects: [2, 4],
    og_title: 'Nupe Artisanal Glass & Brass Photography in Bida — Gold Akingbade',
    og_description: 'Documenting centuries of molten glass and brass craftsmanship in Bida, Niger State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // ABIA STATE
  {
    id: 35,
    location_name: 'Aba',
    state: 'Abia State',
    url_slug: 'photographer-in-aba',
    seo_title: 'Photographer in Aba, Abia State | Leathercraft, Fashion Manufacturing & Lookbooks',
    meta_description: 'High-fashion lookbooks, artisanal leathercraft documentation, and industrial monograph photography in Aba, Abia State. Commercial brilliance and bespoke editorial direction.',
    primary_keyword: 'photographer in Aba',
    secondary_keywords: 'fashion lookbook photographer Aba, leather artisan photography Abia, commercial campaign Aba, industrial monographs',
    location_content: 'As the vibrant epicentre of African apparel and leather craftsmanship, Aba offers a gritty, high-energy industrial setting for bold fashion lookbooks, artisanal workshop portraits, and dynamic commercial campaigns.',
    services_offered: 'Fashion Lookbook Campaigns, Leathercraft Monographs, Industrial Visual Direction, Commercial Portraits',
    related_projects: [1, 4],
    og_title: 'Fashion Manufacturing & Lookbook Photography in Aba — Gold Akingbade',
    og_description: 'Artisanal leathercraft and bold fashion lookbooks created in Aba, Abia State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 36,
    location_name: 'Umuahia',
    state: 'Abia State',
    url_slug: 'photographer-in-umuahia',
    seo_title: 'Photographer in Umuahia, Abia State | Heritage Archives & Fine Art Portraits',
    meta_description: 'Fine art portraiture, National War Museum historical archives, and agricultural landscape photography in Umuahia, Abia State. Serene eastern greenery and historical memory.',
    primary_keyword: 'photographer in Umuahia',
    secondary_keywords: 'portrait photographer Umuahia, Abia State fine art photography, war museum documentation, cultural archives',
    location_content: 'Umuahia provides a quiet, introspective atmosphere amidst rolling cassava hills and historic museum grounds, fostering deeply personal portraiture and historical visual essays.',
    services_offered: 'Historical Visual Essays, Landscape Monographs, Family Archives, Private Portraits',
    related_projects: [3, 5],
    og_title: 'Heritage & Fine Art Photography in Umuahia — Gold Akingbade',
    og_description: 'Introspective portrait sessions and historical archives captured in Umuahia, Abia State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.75,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // BAYELSA STATE
  {
    id: 37,
    location_name: 'Yenagoa',
    state: 'Bayelsa State',
    url_slug: 'photographer-in-yenagoa',
    seo_title: 'Photographer in Yenagoa, Bayelsa State | Mangrove Creek Monograph & Ijaw Heritage',
    meta_description: 'Fine art coastal photography, mangrove estuary monographs, and Ijaw cultural regalia portraiture in Yenagoa, Bayelsa State. Misty wetlands and tranquil riverine light.',
    primary_keyword: 'photographer in Yenagoa',
    secondary_keywords: 'fine art photographer Yenagoa, Ijaw cultural portraiture, mangrove estuary photography Bayelsa, Niger Delta fine art',
    location_content: 'Surrounded by winding freshwater creeks, mangrove forests, and tranquil canoe waterways, Yenagoa offers a poetic, ethereal mist-filtered lighting that elevates cultural Ijaw regalia and wetland landscape monographs.',
    services_offered: 'Wetland Landscape Series, Ijaw Regalia Archives, Riverine Fine Art, Cultural Portraits',
    related_projects: [2, 5],
    og_title: 'Mangrove & Ijaw Cultural Photography in Yenagoa — Gold Akingbade',
    og_description: 'Ethereal wetland landscapes and Ijaw cultural regalia monographs in Yenagoa, Bayelsa State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // KOGI STATE
  {
    id: 38,
    location_name: 'Lokoja',
    state: 'Kogi State',
    url_slug: 'photographer-in-lokoja',
    seo_title: 'Photographer in Lokoja, Kogi State | Confluence of Niger & Benue Rivers Fine Art',
    meta_description: 'River confluence landscape photography, Mount Patti highland monographs, and colonial historical architecture in Lokoja, Kogi State. Dramatic geological meeting of waters.',
    primary_keyword: 'photographer in Lokoja',
    secondary_keywords: 'confluence photographer Lokoja, Mount Patti landscape photography, Kogi state fine art, colonial heritage portraits',
    location_content: 'Standing atop Mount Patti overlooking the legendary confluence where the green waters of the Niger meet the grey waters of the Benue. Monograph shoots utilize panoramic river vistas and colonial stone structures under sweeping golden skies.',
    services_offered: 'Confluence Landscape Monographs, Mount Patti Highland Series, Historical Architecture, Fine Art Prints',
    related_projects: [3, 5],
    og_title: 'River Confluence Fine Art Photography in Lokoja — Gold Akingbade',
    og_description: 'Panoramic river confluence and Mount Patti highland photography in Lokoja, Kogi State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // ADAMAWA STATE
  {
    id: 39,
    location_name: 'Yola',
    state: 'Adamawa State',
    url_slug: 'photographer-in-yola',
    seo_title: 'Photographer in Yola, Adamawa State | Mandara Mountains & Fulani Fine Art',
    meta_description: 'Fine art portraiture, Fulani cultural monographs, and Mandara Mountain landscape photography in Yola, Adamawa State. Sunlit savanna plains and pastoral elegance.',
    primary_keyword: 'photographer in Yola',
    secondary_keywords: 'fine art photographer Yola, Fulani pastoral monographs Adamawa, Mandara mountains photography, savanna landscape',
    location_content: 'Set against the dramatic volcanic peaks of the Mandara ranges and the fertile Benue valley, Yola visual studies highlight pastoral nomadic elegance, hand-embroidered Fulani textiles, and crystalline savanna light.',
    services_offered: 'Pastoral Monograph Series, Mandara Mountain Landscapes, Cultural Portraits, Fine Art Prints',
    related_projects: [2, 5],
    og_title: 'Mandara Mountains & Pastoral Photography in Yola — Gold Akingbade',
    og_description: 'Documenting Fulani cultural heritage and volcanic mountain vistas in Yola, Adamawa State.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  },

  // KATSINA STATE
  {
    id: 40,
    location_name: 'Katsina',
    state: 'Katsina State',
    url_slug: 'photographer-in-katsina',
    seo_title: 'Photographer in Katsina | Gobarau Minaret Architectural Chiaroscuro & Royal Heritage',
    meta_description: 'Ancient mud-brick architectural photography, Gobarau Minaret monographs, and royal Durbar portraiture in historic Katsina City. Sahelian twilight and classical Islamic craft.',
    primary_keyword: 'photographer in Katsina',
    secondary_keywords: 'Gobarau minaret photography Katsina, royal durbar photographer Katsina, mud brick architectural chiaroscuro, sahelian fine art',
    location_content: 'The 600-year-old mud-brick Gobarau Minaret and the illustrious palaces of Katsina offer an extraordinary study in desert architecture, intricate earthen relief carvings, and regal equestrian traditions.',
    services_offered: 'Mud Architecture Studies, Royal Durbar Monographs, Sahelian Portraiture, Historical Archives',
    related_projects: [4, 5],
    og_title: 'Architectural Heritage Photography in Katsina — Gold Akingbade',
    og_description: 'Ancient minarets, earthen relief architecture, and royal monographs in Katsina City.',
    og_image_url: null,
    is_published: true,
    is_indexable: true,
    sitemap_priority: 0.8,
    created_at: new Date(),
    updated_at: new Date(),
  }
];
