import { PhotoAsset } from '../types/portfolio';

export interface StackItem {
  id: string;
  photo: PhotoAsset;
  initialX: number; // translation in px
  initialY: number; // translation in px
  targetX: number; // translation in px
  targetY: number; // translation in px
  rotation: number; // subtle physical print rotation degrees
  delayMs: number;
  zIndex: number;
  width: string;
  height: string;
}

// 10 Curated physical photographic prints for the central stacking sequence
// Assets reside in /assets/splash-images/ and follow the splash-N naming pattern
export const INTRO_STACK_ITEMS: StackItem[] = [
  {
    id: 'splash-1',
    photo: {
      id: 'sp-1',
      projectId: '1',
      filename: 'splash-1.jpg',
      src: '/assets/splash-images/splash-1.jpg',
      fallbackSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
      title: 'Adunni in Ochre',
      projectCode: '01',
      projectName: 'The Silhouettes of Eko',
      year: '2025',
      location: 'Lagos, NG',
      aspectRatio: '3/4',
      widthClass: 'w-44 sm:w-56 md:w-64',
      heightClass: 'h-60 sm:h-76 md:h-88',
      category: 'fashion',
    },
    initialX: -60,
    initialY: -70,
    targetX: -35,
    targetY: -25,
    rotation: -2.2,
    delayMs: 400,
    zIndex: 1,
    width: 'w-44 sm:w-56 md:w-64',
    height: 'h-60 sm:h-76 md:h-88',
  },
  {
    id: 'splash-2',
    photo: {
      id: 'sp-2',
      projectId: '2',
      filename: 'splash-2.jpg',
      src: '/assets/splash-images/splash-2.jpg',
      fallbackSrc: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
      title: 'Nocturne Drapery',
      projectCode: '02',
      projectName: 'Indigo Resonance',
      year: '2024',
      location: 'Akure, NG',
      aspectRatio: '4/5',
      widthClass: 'w-40 sm:w-52 md:w-56',
      heightClass: 'h-52 sm:h-68 md:h-76',
      category: 'editorial',
    },
    initialX: 60,
    initialY: -50,
    targetX: 30,
    targetY: -35,
    rotation: 2.4,
    delayMs: 650,
    zIndex: 2,
    width: 'w-40 sm:w-52 md:w-56',
    height: 'h-52 sm:h-68 md:h-76',
  },
  {
    id: 'splash-3',
    photo: {
      id: 'sp-3',
      projectId: '1',
      filename: 'splash-3.jpg',
      src: '/assets/splash-images/splash-3.jpg',
      fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
      title: 'Sunlit Monolith',
      projectCode: '01',
      projectName: 'The Silhouettes of Eko',
      year: '2025',
      location: 'Lagos, NG',
      aspectRatio: '2/3',
      widthClass: 'w-40 sm:w-50 md:w-56',
      heightClass: 'h-58 sm:h-74 md:h-84',
      category: 'fashion',
    },
    initialX: -40,
    initialY: 50,
    targetX: -20,
    targetY: 30,
    rotation: -1.5,
    delayMs: 900,
    zIndex: 3,
    width: 'w-40 sm:w-50 md:w-56',
    height: 'h-58 sm:h-74 md:h-84',
  },
  {
    id: 'splash-4',
    photo: {
      id: 'sp-4',
      projectId: '3',
      filename: 'splash-4.jpg',
      src: '/assets/splash-images/splash-4.jpg',
      fallbackSrc: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=800&q=80',
      title: 'Terracotta Gaze',
      projectCode: '03',
      projectName: 'Red Earth & Clay',
      year: '2024',
      location: 'Ondo, NG',
      aspectRatio: '1/1',
      widthClass: 'w-38 sm:w-48 md:w-52',
      heightClass: 'h-38 sm:h-48 md:h-52',
      category: 'portrait',
    },
    initialX: 50,
    initialY: 40,
    targetX: 35,
    targetY: 20,
    rotation: 1.8,
    delayMs: 1150,
    zIndex: 4,
    width: 'w-38 sm:w-48 md:w-52',
    height: 'h-38 sm:h-48 md:h-52',
  },
  {
    id: 'splash-5',
    photo: {
      id: 'sp-5',
      projectId: '3',
      filename: 'splash-5.jpg',
      src: '/assets/splash-images/splash-5.jpg',
      fallbackSrc: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=80',
      title: 'Solitude of Idanre',
      projectCode: '03',
      projectName: 'Red Earth & Clay',
      year: '2025',
      location: 'Idanre Hills, NG',
      aspectRatio: '3/4',
      widthClass: 'w-42 sm:w-52 md:w-60',
      heightClass: 'h-56 sm:h-70 md:h-80',
      category: 'portrait',
    },
    initialX: -55,
    initialY: -10,
    targetX: -30,
    targetY: -5,
    rotation: -2.8,
    delayMs: 1400,
    zIndex: 5,
    width: 'w-42 sm:w-52 md:w-60',
    height: 'h-56 sm:h-70 md:h-80',
  },
  {
    id: 'splash-6',
    photo: {
      id: 'sp-6',
      projectId: '4',
      filename: 'splash-6.jpg',
      src: '/assets/splash-images/splash-6.jpg',
      fallbackSrc: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
      title: 'Aso-Oke Motion Study',
      projectCode: '04',
      projectName: 'Woven Formations',
      year: '2025',
      location: 'Lagos, NG',
      aspectRatio: '4/3',
      widthClass: 'w-48 sm:w-60 md:w-68',
      heightClass: 'h-36 sm:h-46 md:h-52',
      category: 'art-direction',
    },
    initialX: 45,
    initialY: -30,
    targetX: 25,
    targetY: -15,
    rotation: 1.2,
    delayMs: 1650,
    zIndex: 6,
    width: 'w-48 sm:w-60 md:w-68',
    height: 'h-36 sm:h-46 md:h-52',
  },
  {
    id: 'splash-7',
    photo: {
      id: 'sp-7',
      projectId: '2',
      filename: 'splash-7.jpg',
      src: '/assets/splash-images/splash-7.jpg',
      fallbackSrc: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=800&q=80',
      title: 'The Gilded Veil',
      projectCode: '02',
      projectName: 'Indigo Resonance',
      year: '2024',
      location: 'Akure, NG',
      aspectRatio: '3/4',
      widthClass: 'w-40 sm:w-50 md:w-56',
      heightClass: 'h-54 sm:h-68 md:h-76',
      category: 'fashion',
    },
    initialX: -25,
    initialY: 45,
    targetX: -10,
    targetY: 25,
    rotation: -0.9,
    delayMs: 1900,
    zIndex: 7,
    width: 'w-40 sm:w-50 md:w-56',
    height: 'h-54 sm:h-68 md:h-76',
  },
  {
    id: 'splash-8',
    photo: {
      id: 'sp-8',
      projectId: '4',
      filename: 'splash-8.jpg',
      src: '/assets/splash-images/splash-8.jpg',
      fallbackSrc: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
      title: 'Contemplation at Dusk',
      projectCode: '04',
      projectName: 'Woven Formations',
      year: '2025',
      location: 'Lagos, NG',
      aspectRatio: '4/5',
      widthClass: 'w-44 sm:w-54 md:w-60',
      heightClass: 'h-56 sm:h-70 md:h-80',
      category: 'portrait',
    },
    initialX: 35,
    initialY: 20,
    targetX: 15,
    targetY: 5,
    rotation: 1.5,
    delayMs: 2150,
    zIndex: 8,
    width: 'w-44 sm:w-54 md:w-60',
    height: 'h-56 sm:h-70 md:h-80',
  },
  {
    id: 'splash-9',
    photo: {
      id: 'sp-9',
      projectId: '1',
      filename: 'splash-9.jpg',
      src: '/assets/splash-images/splash-9.jpg',
      fallbackSrc: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
      title: 'Architectural Linen',
      projectCode: '01',
      projectName: 'The Silhouettes of Eko',
      year: '2025',
      location: 'Lagos, NG',
      aspectRatio: '3/4',
      widthClass: 'w-42 sm:w-52 md:w-58',
      heightClass: 'h-58 sm:h-72 md:h-82',
      category: 'fashion',
    },
    initialX: -45,
    initialY: -40,
    targetX: -20,
    targetY: -20,
    rotation: -1.7,
    delayMs: 2400,
    zIndex: 9,
    width: 'w-42 sm:w-52 md:w-58',
    height: 'h-58 sm:h-72 md:h-82',
  },
  {
    id: 'splash-10',
    photo: {
      id: 'sp-10',
      projectId: '3',
      filename: 'splash-10.jpg',
      src: '/assets/splash-images/splash-10.jpg',
      fallbackSrc: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=800&q=80',
      title: 'Kola Nut & Amber',
      projectCode: '03',
      projectName: 'Red Earth & Clay',
      year: '2024',
      location: 'Akure, NG',
      aspectRatio: '4/5',
      widthClass: 'w-46 sm:w-56 md:w-62',
      heightClass: 'h-60 sm:h-74 md:h-84',
      category: 'portrait',
    },
    initialX: 20,
    initialY: -15,
    targetX: 0,
    targetY: 0,
    rotation: 0.4,
    delayMs: 2650,
    zIndex: 10,
    width: 'w-46 sm:w-56 md:w-62',
    height: 'h-60 sm:h-74 md:h-84',
  },
];
