import { PhotoAsset, ProjectGallery, SocialLink } from '../types/portfolio';

/**
 * Centralized external URL for studio design credit in footer
 */
export const CASTEL_STUDIOS_URL = 'https://castelstudios.com';

export const SOCIAL_LINKS: SocialLink[] = [
  { id: 'instagram', label: 'INSTAGRAM', href: 'https://instagram.com' },
  { id: 'tiktok', label: 'TIKTOK', href: 'https://tiktok.com' },
  { id: 'pixieset', label: 'PIXIESET', href: 'https://pixieset.com' },
  { id: 'pinterest', label: 'PINTEREST', href: 'https://pinterest.com' },
  { id: 'whatsapp', label: 'WHATSAPP', href: 'https://whatsapp.com' },
];

/**
 * FIVE PROJECTS CENTRALIZED DATA MODEL
 *
 * ASSET NAMING CONTRACT:
 * - UPPER/FRONT HOMEPAGE TRACK:  /assets/front-1.jpg ... /assets/front-5.jpg
 * - LOWER/BACK HOMEPAGE TRACK:   /assets/back-1.jpg ... /assets/back-5.jpg
 * - PROJECT GALLERY IMAGES:      /assets/project/PROJ-X.Y.jpg (5 projects × 6 images = 30 images)
 */
export const PROJECTS_GALLERY: ProjectGallery[] = [
  // =========================================================================
  // PROJECT 1: The Silhouettes of Eko
  // =========================================================================
  {
    id: '1',
    code: '01',
    slug: '1',
    title: 'The Silhouettes of Eko',
    statement: '“A study of identity, architectural movement and quiet confidence through contemporary Nigerian high fashion.”',
    subtitle: 'High-fashion editorial across contemporary Lagos landscapes',
    year: '2025',
    location: 'Lagos, Nigeria',
    category: 'FASHION',
    story: 'An exploration of architectural form, fluid draping, and modern West African identity staged against the coastal light and modernist structures of Lagos Island. Photographed on medium format analog-emulation sensor across three distinct light temperatures, the series investigates how sculptural tailoring interacts with maritime wind and raw urban surfaces.',
    client: 'Vogue Africa / Commissioned Spread',
    creativeDirection: 'Gold Akingbade Studio',
    styling: 'Bamidele Cole',
    description: 'An exploration of architectural form, fluid draping, and modern West African identity staged against the coastal light and modernist structures of Lagos Island.',
    coverImage: '/assets/project/PROJ-1.1.jpg',
    nextProjectSlug: '2',
    prevProjectSlug: '5',
    homepageImages: [
      {
        id: 'front-1',
        projectId: '1',
        filename: 'front-1.jpg',
        src: '/assets/front-1.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=85',
        title: 'Adunni in Ochre',
        projectCode: '01',
        projectName: 'The Silhouettes of Eko',
        year: '2025',
        location: 'Lagos, NG',
        aspectRatio: '3/4',
        widthClass: 'w-44 sm:w-52 md:w-60 lg:w-64',
        heightClass: 'h-60 sm:h-70 md:h-80 lg:h-88',
        verticalOffset: 'translate-y-0',
        category: 'fashion',
      },
      {
        id: 'back-1',
        projectId: '1',
        filename: 'back-1.jpg',
        src: '/assets/back-1.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?auto=format&fit=crop&w=1000&q=85',
        title: 'Saffron Draping',
        projectCode: '01',
        projectName: 'The Silhouettes of Eko',
        year: '2025',
        location: 'Lagos, NG',
        aspectRatio: '16/10',
        widthClass: 'w-56 sm:w-64 md:w-76 lg:w-84',
        heightClass: 'h-36 sm:h-44 md:h-48 lg:h-52',
        verticalOffset: 'translate-y-2 md:translate-y-4',
        category: 'editorial',
      },
    ],
    images: [
      {
        id: 'p1-1',
        filename: 'PROJ-1.1.jpg',
        src: '/assets/project/PROJ-1.1.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
        caption: 'Adunni in Ochre Silk — Marina Shoreline',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'lead-feature',
        plateNumber: 'Plate 01/06',
        subtitle: 'Natural diffused morning light over the Atlantic breakwater',
      },
      {
        id: 'p1-2',
        filename: 'PROJ-1.2.jpg',
        src: '/assets/project/PROJ-1.2.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
        caption: 'Sunlit Monolith in Canary Draping',
        aspectRatio: '2/3',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 02/06',
        subtitle: 'Geometric tailoring against brutalist concrete',
      },
      {
        id: 'p1-3',
        filename: 'PROJ-1.3.jpg',
        src: '/assets/project/PROJ-1.3.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?auto=format&fit=crop&w=1400&q=85',
        caption: 'Saffron Draping on Reclaimed Concrete',
        aspectRatio: '16/10',
        orientation: 'landscape',
        layoutRole: 'wide-spread',
        plateNumber: 'Plate 03/06',
        subtitle: 'Panoramic perspective of raw linen in maritime wind',
      },
      {
        id: 'p1-4',
        filename: 'PROJ-1.4.jpg',
        src: '/assets/project/PROJ-1.4.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1200&q=85',
        caption: 'Architectural Linen study at twilight',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 04/06',
        subtitle: 'Micro-weave detail and dusk illumination',
      },
      {
        id: 'p1-5',
        filename: 'PROJ-1.5.jpg',
        src: '/assets/project/PROJ-1.5.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
        caption: 'Mirage of Victoria Island',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 05/06',
        subtitle: 'Low-angle study in layered organza and light refraction',
      },
      {
        id: 'p1-6',
        filename: 'PROJ-1.6.jpg',
        src: '/assets/project/PROJ-1.6.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1400&q=85',
        caption: 'Golden Hour at Bar Beach Archive',
        aspectRatio: '4/3',
        orientation: 'landscape',
        layoutRole: 'standalone',
        plateNumber: 'Plate 06/06',
        subtitle: 'Concluding tableau under fading coastal warmth',
      },
    ],
  },

  // =========================================================================
  // PROJECT 2: Indigo Resonance
  // =========================================================================
  {
    id: '2',
    code: '02',
    slug: '2',
    title: 'Indigo Resonance',
    statement: '“Documenting the tactile richness of deep indigo pigments, ancestral shadow play, and sacred textile traditions.”',
    subtitle: 'Sacred hues and handcrafted indigo dyes of Yorubaland',
    year: '2024',
    location: 'Akure, Nigeria',
    category: 'TEXTILE & EDITORIAL',
    story: 'A dedicated visual monograph exploring the organic fermentation of natural indigo vats, hand-resist Adire textiles, and the luminous interplay of sunlight piercing open-air dye pits in southwestern Nigeria. The photographic series documents how ancestral dyeing traditions transmute raw calico into deep celestial blues.',
    client: 'Independent Research & Arthouse Commission',
    creativeDirection: 'Gold Akingbade',
    styling: 'Toluwani Ojo',
    description: 'A dedicated monograph on the organic fermentation of indigo vats, hand-resist Adire textiles, and the luminous interplay of natural sunlight piercing open-air dye compounds in southwestern Nigeria.',
    coverImage: '/assets/project/PROJ-2.1.jpg',
    nextProjectSlug: '3',
    prevProjectSlug: '1',
    homepageImages: [
      {
        id: 'front-2',
        projectId: '2',
        filename: 'front-2.jpg',
        src: '/assets/front-2.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=85',
        title: 'Nocturne Drapery',
        projectCode: '02',
        projectName: 'Indigo Resonance',
        year: '2024',
        location: 'Akure, NG',
        aspectRatio: '4/5',
        widthClass: 'w-40 sm:w-48 md:w-56 lg:w-60',
        heightClass: 'h-54 sm:h-64 md:h-74 lg:h-80',
        verticalOffset: 'translate-y-2 sm:translate-y-4',
        category: 'editorial',
      },
      {
        id: 'back-2',
        projectId: '2',
        filename: 'back-2.jpg',
        src: '/assets/back-2.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1000&q=85',
        title: 'The Gilded Veil',
        projectCode: '02',
        projectName: 'Indigo Resonance',
        year: '2024',
        location: 'Akure, NG',
        aspectRatio: '3/4',
        widthClass: 'w-42 sm:w-50 md:w-58 lg:w-64',
        heightClass: 'h-56 sm:h-68 md:h-78 lg:h-84',
        verticalOffset: 'translate-y-0',
        category: 'fashion',
      },
    ],
    images: [
      {
        id: 'p2-1',
        filename: 'PROJ-2.1.jpg',
        src: '/assets/project/PROJ-2.1.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=85',
        caption: 'The Fermentation Vat at Dawn',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'lead-feature',
        plateNumber: 'Plate 01/06',
        subtitle: 'Natural indigo froth and early morning dew reflection',
      },
      {
        id: 'p2-2',
        filename: 'PROJ-2.2.jpg',
        src: '/assets/project/PROJ-2.2.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1200&q=85',
        caption: 'Veil of Hand-Resist Adire Eleko',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 02/06',
        subtitle: 'Intricate cassava starch resist patterns drying in shade',
      },
      {
        id: 'p2-3',
        filename: 'PROJ-2.3.jpg',
        src: '/assets/project/PROJ-2.3.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1400&q=85',
        caption: 'Drying Yard under Equatorial Light',
        aspectRatio: '16/10',
        orientation: 'landscape',
        layoutRole: 'wide-spread',
        plateNumber: 'Plate 03/06',
        subtitle: 'Tension lines holding yards of saturated indigo calico',
      },
      {
        id: 'p2-4',
        filename: 'PROJ-2.4.jpg',
        src: '/assets/project/PROJ-2.4.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=85',
        caption: 'Portrait with Indigo Hands',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 04/06',
        subtitle: 'Master dyer hands stained in celestial Prussian blue',
      },
      {
        id: 'p2-5',
        filename: 'PROJ-2.5.jpg',
        src: '/assets/project/PROJ-2.5.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
        caption: 'Architectural Shadow over Loom',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 05/06',
        subtitle: 'Direct high-noon sunlight casting lattice geometry',
      },
      {
        id: 'p2-6',
        filename: 'PROJ-2.6.jpg',
        src: '/assets/project/PROJ-2.6.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1400&q=85',
        caption: 'Indigo Nocturne in Movement',
        aspectRatio: '4/3',
        orientation: 'landscape',
        layoutRole: 'standalone',
        plateNumber: 'Plate 06/06',
        subtitle: 'Long exposure capture of draped silk responding to twilight breeze',
      },
    ],
  },

  // =========================================================================
  // PROJECT 3: Red Earth & Clay
  // =========================================================================
  {
    id: '3',
    code: '03',
    slug: '3',
    title: 'Red Earth & Clay',
    statement: '“An ode to the sacred granite monoliths, red laterite soils, and organic stillness of ancient highland settlements.”',
    subtitle: 'Earth pigments, warm skin tones, and granite monoliths of Ondo',
    year: '2024',
    location: 'Idanre Hills & Ondo, Nigeria',
    category: 'FINE ART & FASHION',
    story: 'Staged across the ancient stone stairways and rich red laterite soil of the historic Idanre mountain settlement. The interplay of ancient mineral textures, warm ochre skin tones, and crisp minimalist tailoring creates a quiet, contemplative visual dialogue rooted in the landscape.',
    client: 'Arthouse Heritage / Solo Monograph',
    creativeDirection: 'Gold Akingbade',
    styling: 'Folake Adeleke',
    description: 'Staged across the ancient stone stairways and red laterite soil of the historic Idanre mountain settlement.',
    coverImage: '/assets/project/PROJ-3.1.jpg',
    nextProjectSlug: '4',
    prevProjectSlug: '2',
    homepageImages: [
      {
        id: 'front-3',
        projectId: '3',
        filename: 'front-3.jpg',
        src: '/assets/front-3.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1000&q=85',
        title: 'Terracotta Gaze',
        projectCode: '03',
        projectName: 'Red Earth & Clay',
        year: '2024',
        location: 'Ondo, NG',
        aspectRatio: '1/1',
        widthClass: 'w-40 sm:w-48 md:w-56 lg:w-60',
        heightClass: 'h-40 sm:h-48 md:h-56 lg:h-60',
        verticalOffset: 'translate-y-1 sm:translate-y-3',
        category: 'portrait',
      },
      {
        id: 'back-3',
        projectId: '3',
        filename: 'back-3.jpg',
        src: '/assets/back-3.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1000&q=85',
        title: 'Solitude of Idanre',
        projectCode: '03',
        projectName: 'Red Earth & Clay',
        year: '2025',
        location: 'Idanre Hills, NG',
        aspectRatio: '3/4',
        widthClass: 'w-44 sm:w-52 md:w-60 lg:w-66',
        heightClass: 'h-58 sm:h-70 md:h-80 lg:h-88',
        verticalOffset: 'translate-y-3 sm:translate-y-6',
        category: 'portrait',
      },
    ],
    images: [
      {
        id: 'p3-1',
        filename: 'PROJ-3.1.jpg',
        src: '/assets/project/PROJ-3.1.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=85',
        caption: 'Terracotta Gaze atop Idanre Ridge',
        aspectRatio: '1/1',
        orientation: 'square',
        layoutRole: 'lead-feature',
        plateNumber: 'Plate 01/06',
        subtitle: 'Warm laterite dust and midday cloud shadows',
      },
      {
        id: 'p3-2',
        filename: 'PROJ-3.2.jpg',
        src: '/assets/project/PROJ-3.2.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=85',
        caption: 'Monolith Ascendance in Raw Linen',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 02/06',
        subtitle: 'Granite surface textures weathered across centuries',
      },
      {
        id: 'p3-3',
        filename: 'PROJ-3.3.jpg',
        src: '/assets/project/PROJ-3.3.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1400&q=85',
        caption: 'Panorama across the Misty Valley',
        aspectRatio: '16/10',
        orientation: 'landscape',
        layoutRole: 'wide-spread',
        plateNumber: 'Plate 03/06',
        subtitle: 'Harmattan haze rolling over highland forest canopies',
      },
      {
        id: 'p3-4',
        filename: 'PROJ-3.4.jpg',
        src: '/assets/project/PROJ-3.4.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
        caption: 'Earthen Vessel and Ochre Pigment',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 04/06',
        subtitle: 'Traditional pottery clay harmonizing with structured collar',
      },
      {
        id: 'p3-5',
        filename: 'PROJ-3.5.jpg',
        src: '/assets/project/PROJ-3.5.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
        caption: 'Stone Steps to the Ancient Palace',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 05/06',
        subtitle: 'The 660 steps leading into timeless mountain sanctuary',
      },
      {
        id: 'p3-6',
        filename: 'PROJ-3.6.jpg',
        src: '/assets/project/PROJ-3.6.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1400&q=85',
        caption: 'Dusk over the Granite Domes',
        aspectRatio: '4/3',
        orientation: 'landscape',
        layoutRole: 'standalone',
        plateNumber: 'Plate 06/06',
        subtitle: 'Deep amber horizon silhouette closing the highland chapter',
      },
    ],
  },

  // =========================================================================
  // PROJECT 4: Woven Formations
  // =========================================================================
  {
    id: '4',
    code: '04',
    slug: '4',
    title: 'Woven Formations',
    statement: '“Deconstructing traditional Yoruba weaving techniques through dynamic physical motion and high-contrast sculptural forms.”',
    subtitle: 'Ceremonial weaving, contemporary silhouettes, and sculptural volume',
    year: '2025',
    location: 'Lagos & Oyo, Nigeria',
    category: 'SCULPTURAL FASHION',
    story: 'Focusing on heavy hand-loomed Aso-Oke weaves reinterpreted into contemporary geometric coats and monumental silhouettes. Each frame emphasizes the tactile tension of metallic threads, raw cotton slubs, and human grace captured in dynamic studio motion.',
    client: 'Design Biennial Selection / Exhibition',
    creativeDirection: 'Gold Akingbade',
    styling: 'Kolawole Badmus',
    description: 'Focusing on heavy hand-loomed Aso-Oke weaves reinterpreted into contemporary geometric coats and monumental silhouettes.',
    coverImage: '/assets/project/PROJ-4.1.jpg',
    nextProjectSlug: '5',
    prevProjectSlug: '3',
    homepageImages: [
      {
        id: 'front-4',
        projectId: '4',
        filename: 'front-4.jpg',
        src: '/assets/front-4.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1000&q=85',
        title: 'Aso-Oke Motion Study',
        projectCode: '04',
        projectName: 'Woven Formations',
        year: '2025',
        location: 'Lagos, NG',
        aspectRatio: '4/3',
        widthClass: 'w-48 sm:w-58 md:w-68 lg:w-76',
        heightClass: 'h-36 sm:h-44 md:h-52 lg:h-58',
        verticalOffset: 'translate-y-0',
        category: 'art-direction',
      },
      {
        id: 'back-4',
        projectId: '4',
        filename: 'back-4.jpg',
        src: '/assets/back-4.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=85',
        title: 'Contemplation at Dusk',
        projectCode: '04',
        projectName: 'Woven Formations',
        year: '2025',
        location: 'Lagos, NG',
        aspectRatio: '4/5',
        widthClass: 'w-44 sm:w-52 md:w-60 lg:w-64',
        heightClass: 'h-56 sm:h-68 md:h-76 lg:h-82',
        verticalOffset: 'translate-y-1 sm:translate-y-3',
        category: 'portrait',
      },
    ],
    images: [
      {
        id: 'p4-1',
        filename: 'PROJ-4.1.jpg',
        src: '/assets/project/PROJ-4.1.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85',
        caption: 'The Metallic Aso-Oke Cape in Flight',
        aspectRatio: '4/3',
        orientation: 'landscape',
        layoutRole: 'lead-feature',
        plateNumber: 'Plate 01/06',
        subtitle: 'High-speed shutter freeze of hand-woven lurex and raw silk',
      },
      {
        id: 'p4-2',
        filename: 'PROJ-4.2.jpg',
        src: '/assets/project/PROJ-4.2.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
        caption: 'Sculptural Collar Detail',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 02/06',
        subtitle: 'Macro lens focal plane on hand-intertwined warp fibers',
      },
      {
        id: 'p4-3',
        filename: 'PROJ-4.3.jpg',
        src: '/assets/project/PROJ-4.3.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1400&q=85',
        caption: 'The Double Loom Ensemble',
        aspectRatio: '16/10',
        orientation: 'landscape',
        layoutRole: 'wide-spread',
        plateNumber: 'Plate 03/06',
        subtitle: 'Two models framed against towering floor-to-ceiling looms in Iseyin',
      },
      {
        id: 'p4-4',
        filename: 'PROJ-4.4.jpg',
        src: '/assets/project/PROJ-4.4.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1200&q=85',
        caption: 'Ochre and Obsidian Checkers',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 04/06',
        subtitle: 'Ceremonial check motif reimagined into minimal overcoat',
      },
      {
        id: 'p4-5',
        filename: 'PROJ-4.5.jpg',
        src: '/assets/project/PROJ-4.5.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
        caption: 'Kinetic Movement Study #3',
        aspectRatio: '2/3',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 05/06',
        subtitle: 'Intentional motion blur highlighting heavy textile weight',
      },
      {
        id: 'p4-6',
        filename: 'PROJ-4.6.jpg',
        src: '/assets/project/PROJ-4.6.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1400&q=85',
        caption: 'The Master Weaver Stance',
        aspectRatio: '4/3',
        orientation: 'landscape',
        layoutRole: 'standalone',
        plateNumber: 'Plate 06/06',
        subtitle: 'Direct eye contact framed by hanging spools of spun raw cotton',
      },
    ],
  },

  // =========================================================================
  // PROJECT 5: Monolith & Shadow
  // =========================================================================
  {
    id: '5',
    code: '05',
    slug: '5',
    title: 'Monolith & Shadow',
    statement: '“A minimalist exploration of light architecture, deep chiaroscuro, and sacred geometric geometry.”',
    subtitle: 'Minimalist chiaroscuro and sacred architectural forms',
    year: '2025',
    location: 'Lagos & Abeokuta, Nigeria',
    category: 'ARCHITECTURAL CHIAROSCURO',
    story: 'Documenting the spiritual stillness of modernist ecclesiastical architecture and raw stone compounds. Luminous shafts of coastal sunlight cut through deep architectural shadows, framing sculptural silhouettes with serene reverence and timeless balance.',
    client: 'Monograph / Arthouse Pavilion Selection',
    creativeDirection: 'Gold Akingbade Studio',
    styling: 'Yewande Bakare',
    description: 'Documenting the spiritual stillness of modernist ecclesiastical architecture and raw stone compounds.',
    coverImage: '/assets/project/PROJ-5.1.jpg',
    nextProjectSlug: '1',
    prevProjectSlug: '4',
    homepageImages: [
      {
        id: 'front-5',
        projectId: '5',
        filename: 'front-5.jpg',
        src: '/assets/front-5.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=85',
        title: 'Sunlit Monolith',
        projectCode: '05',
        projectName: 'Monolith & Shadow',
        year: '2025',
        location: 'Lagos, NG',
        aspectRatio: '3/4',
        widthClass: 'w-42 sm:w-50 md:w-58 lg:w-62',
        heightClass: 'h-58 sm:h-70 md:h-80 lg:h-86',
        verticalOffset: 'translate-y-0',
        category: 'fashion',
      },
      {
        id: 'back-5',
        projectId: '5',
        filename: 'back-5.jpg',
        src: '/assets/back-5.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=85',
        title: 'Kola Nut & Amber',
        projectCode: '05',
        projectName: 'Monolith & Shadow',
        year: '2025',
        location: 'Akure, NG',
        aspectRatio: '4/5',
        widthClass: 'w-46 sm:w-54 md:w-62 lg:w-66',
        heightClass: 'h-60 sm:h-72 md:h-82 lg:h-88',
        verticalOffset: 'translate-y-2 sm:translate-y-4',
        category: 'portrait',
      },
    ],
    images: [
      {
        id: 'p5-1',
        filename: 'PROJ-5.1.jpg',
        src: '/assets/project/PROJ-5.1.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
        caption: 'Sanctuary in Morning Chiaroscuro',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'lead-feature',
        plateNumber: 'Plate 01/06',
        subtitle: 'Single angular beam piercing high vaulted masonry',
      },
      {
        id: 'p5-2',
        filename: 'PROJ-5.2.jpg',
        src: '/assets/project/PROJ-5.2.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
        caption: 'Aura in Unbleached Silk',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 02/06',
        subtitle: 'Direct contemplative gaze framed by geometric arches',
      },
      {
        id: 'p5-3',
        filename: 'PROJ-5.3.jpg',
        src: '/assets/project/PROJ-5.3.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1400&q=85',
        caption: 'The Cloister Promenade',
        aspectRatio: '16/10',
        orientation: 'landscape',
        layoutRole: 'wide-spread',
        plateNumber: 'Plate 03/06',
        subtitle: 'Sweeping horizontal composition along limestone colonnade',
      },
      {
        id: 'p5-4',
        filename: 'PROJ-5.4.jpg',
        src: '/assets/project/PROJ-5.4.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=85',
        caption: 'Study in Contrast and Obsidian Wool',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 04/06',
        subtitle: 'Deep chiaroscuro shadow carving sculptural cheekbones',
      },
      {
        id: 'p5-5',
        filename: 'PROJ-5.5.jpg',
        src: '/assets/project/PROJ-5.5.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=85',
        caption: 'The Vestment in Amber Light',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 05/06',
        subtitle: 'Warm reflective glow casting across pleated organza',
      },
      {
        id: 'p5-6',
        filename: 'PROJ-5.6.jpg',
        src: '/assets/project/PROJ-5.6.jpg',
        fallbackSrc: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1400&q=85',
        caption: 'Sanctuary Consecration Finale',
        aspectRatio: '4/3',
        orientation: 'landscape',
        layoutRole: 'standalone',
        plateNumber: 'Plate 06/06',
        subtitle: 'Monumental architectural closure under twilight atmosphere',
      },
    ],
  },
];

/**
 * EXACTLY 10 HOMEPAGE IMAGES (5 FRONT/TOP, 5 BACK/BOTTOM)
 * Derived directly from the 5 projects.
 * Top track: front-1.jpg through front-5.jpg (1 per project)
 * Bottom track: back-1.jpg through back-5.jpg (1 per project)
 */
export const TOP_PHOTO_ASSETS: PhotoAsset[] = PROJECTS_GALLERY.map(
  (project) => project.homepageImages![0]
);

export const BOTTOM_PHOTO_ASSETS: PhotoAsset[] = PROJECTS_GALLERY.map(
  (project) => project.homepageImages![1]
);
