import { PhotoAsset, ProjectGallery, SocialLink } from '../types/portfolio';

// High-end curated editorial photography for homepage tracks
export const TOP_PHOTO_ASSETS: PhotoAsset[] = [
  {
    id: 'top-1',
    filename: '1.jpg',
    src: '/assets/splash-images/1.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=85',
    title: 'Adunni in Ochre',
    projectCode: '01',
    projectName: 'The Silhouettes of Eko',
    year: '2025',
    location: 'Lagos, NG',
    aspectRatio: '3/4',
    widthClass: 'w-44 sm:w-52 md:w-60 lg:w-64',
    heightClass: 'h-60 sm:h-70 md:h-80 lg:h-88',
    verticalOffset: 'translate-y-0',
    category: 'fashion',
  },
  {
    id: 'top-2',
    filename: '2.jpg',
    src: '/assets/splash-images/2.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=85',
    title: 'Nocturne Drapery',
    projectCode: '02',
    projectName: 'Indigo Resonance',
    year: '2024',
    location: 'Akure, NG',
    aspectRatio: '4/5',
    widthClass: 'w-36 sm:w-44 md:w-48 lg:w-52',
    heightClass: 'h-48 sm:h-56 md:h-64 lg:h-72',
    verticalOffset: 'translate-y-2 md:translate-y-3',
    category: 'editorial',
  },
  {
    id: 'top-3',
    filename: '3.jpg',
    src: '/assets/splash-images/3.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=85',
    title: 'Sunlit Monolith',
    projectCode: '01',
    projectName: 'The Silhouettes of Eko',
    year: '2025',
    location: 'Lagos, NG',
    aspectRatio: '2/3',
    widthClass: 'w-48 sm:w-56 md:w-64 lg:w-72',
    heightClass: 'h-64 sm:h-76 md:h-88 lg:h-96',
    verticalOffset: '-translate-y-1 md:-translate-y-2',
    category: 'fashion',
  },
  {
    id: 'top-4',
    filename: '4.jpg',
    src: '/assets/splash-images/4.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1000&q=85',
    title: 'Terracotta Gaze',
    projectCode: '03',
    projectName: 'Red Earth & Clay',
    year: '2024',
    location: 'Ondo, NG',
    aspectRatio: '1/1',
    widthClass: 'w-40 sm:w-48 md:w-56 lg:w-60',
    heightClass: 'h-40 sm:h-48 md:h-56 lg:h-60',
    verticalOffset: 'translate-y-3 md:translate-y-4',
    category: 'portrait',
  },
  {
    id: 'top-5',
    filename: '5.jpg',
    src: '/assets/splash-images/5.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1000&q=85',
    title: 'Solitude of Idanre',
    projectCode: '03',
    projectName: 'Red Earth & Clay',
    year: '2025',
    location: 'Idanre Hills, NG',
    aspectRatio: '3/4',
    widthClass: 'w-44 sm:w-52 md:w-60 lg:w-64',
    heightClass: 'h-56 sm:h-64 md:h-76 lg:h-84',
    verticalOffset: 'translate-y-1',
    category: 'portrait',
  },
  {
    id: 'top-6',
    filename: '6.jpg',
    src: '/assets/splash-images/6.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1000&q=85',
    title: 'Aso-Oke Motion Study',
    projectCode: '04',
    projectName: 'Woven Formations',
    year: '2025',
    location: 'Lagos, NG',
    aspectRatio: '4/3',
    widthClass: 'w-56 sm:w-64 md:w-72 lg:w-80',
    heightClass: 'h-40 sm:h-48 md:h-52 lg:h-60',
    verticalOffset: 'translate-y-2 md:translate-y-4',
    category: 'art-direction',
  },
  {
    id: 'top-7',
    filename: '7.jpg',
    src: '/assets/splash-images/7.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1000&q=85',
    title: 'The Gilded Veil',
    projectCode: '02',
    projectName: 'Indigo Resonance',
    year: '2024',
    location: 'Akure, NG',
    aspectRatio: '3/4',
    widthClass: 'w-40 sm:w-48 md:w-52 lg:w-56',
    heightClass: 'h-52 sm:h-60 md:h-72 lg:h-80',
    verticalOffset: '-translate-y-1.5',
    category: 'fashion',
  },
  {
    id: 'top-8',
    filename: '8.jpg',
    src: '/assets/splash-images/8.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=85',
    title: 'Contemplation at Dusk',
    projectCode: '04',
    projectName: 'Woven Formations',
    year: '2025',
    location: 'Lagos, NG',
    aspectRatio: '4/5',
    widthClass: 'w-44 sm:w-52 md:w-56 lg:w-64',
    heightClass: 'h-52 sm:h-64 md:h-72 lg:h-80',
    verticalOffset: 'translate-y-1.5',
    category: 'portrait',
  },
  {
    id: 'top-9',
    filename: '9.jpg',
    src: '/assets/splash-images/9.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1000&q=85',
    title: 'Architectural Linen',
    projectCode: '01',
    projectName: 'The Silhouettes of Eko',
    year: '2025',
    location: 'Lagos, NG',
    aspectRatio: '3/4',
    widthClass: 'w-40 sm:w-48 md:w-56 lg:w-60',
    heightClass: 'h-56 sm:h-64 md:h-76 lg:h-84',
    verticalOffset: '-translate-y-1',
    category: 'fashion',
  },
  {
    id: 'top-10',
    filename: '10.jpg',
    src: '/assets/splash-images/10.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1000&q=85',
    title: 'Kola Nut & Amber',
    projectCode: '03',
    projectName: 'Red Earth & Clay',
    year: '2024',
    location: 'Akure, NG',
    aspectRatio: '4/5',
    widthClass: 'w-48 sm:w-56 md:w-60 lg:w-68',
    heightClass: 'h-60 sm:h-70 md:h-80 lg:h-88',
    verticalOffset: 'translate-y-1 md:translate-y-2',
    category: 'portrait',
  }
];

export const BOTTOM_PHOTO_ASSETS: PhotoAsset[] = [
  {
    id: 'bot-1',
    filename: '1.jpg',
    src: '/assets/splash-images/1.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1000&q=85',
    title: 'Elegance in Cobalt',
    projectCode: '02',
    projectName: 'Indigo Resonance',
    year: '2025',
    location: 'Lagos, NG',
    aspectRatio: '4/5',
    widthClass: 'w-40 sm:w-48 md:w-56 lg:w-60',
    heightClass: 'h-48 sm:h-56 md:h-68 lg:h-76',
    verticalOffset: 'translate-y-2 md:translate-y-3',
    category: 'portrait',
  },
  {
    id: 'bot-2',
    filename: '2.jpg',
    src: '/assets/splash-images/2.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1000&q=85',
    title: 'Profile in Raw Umber',
    projectCode: '04',
    projectName: 'Woven Formations',
    year: '2024',
    location: 'Akure, NG',
    aspectRatio: '3/4',
    widthClass: 'w-44 sm:w-52 md:w-60 lg:w-64',
    heightClass: 'h-56 sm:h-64 md:h-76 lg:h-84',
    verticalOffset: '-translate-y-1',
    category: 'portrait',
  },
  {
    id: 'bot-3',
    filename: '3.jpg',
    src: '/assets/splash-images/3.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?auto=format&fit=crop&w=1000&q=85',
    title: 'Saffron Draping',
    projectCode: '01',
    projectName: 'The Silhouettes of Eko',
    year: '2025',
    location: 'Lagos, NG',
    aspectRatio: '16/10',
    widthClass: 'w-56 sm:w-64 md:w-76 lg:w-84',
    heightClass: 'h-36 sm:h-44 md:h-48 lg:h-52',
    verticalOffset: 'translate-y-2 md:translate-y-4',
    category: 'editorial',
  },
  {
    id: 'bot-4',
    filename: '4.jpg',
    src: '/assets/splash-images/4.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=1000&q=85',
    title: 'Study in Bronze Light',
    projectCode: '03',
    projectName: 'Red Earth & Clay',
    year: '2024',
    location: 'Lagos, NG',
    aspectRatio: '3/4',
    widthClass: 'w-36 sm:w-44 md:w-52 lg:w-56',
    heightClass: 'h-48 sm:h-56 md:h-68 lg:h-76',
    verticalOffset: '-translate-y-1.5 md:-translate-y-2',
    category: 'fashion',
  },
  {
    id: 'bot-5',
    filename: '5.jpg',
    src: '/assets/splash-images/5.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1000&q=85',
    title: 'Adire Texture in Flight',
    projectCode: '02',
    projectName: 'Indigo Resonance',
    year: '2025',
    location: 'Akure, NG',
    aspectRatio: '4/5',
    widthClass: 'w-48 sm:w-56 md:w-64 lg:w-68',
    heightClass: 'h-60 sm:h-68 md:h-78 lg:h-86',
    verticalOffset: 'translate-y-1',
    category: 'art-direction',
  },
  {
    id: 'bot-6',
    filename: '6.jpg',
    src: '/assets/splash-images/6.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1000&q=85',
    title: 'The Elder’s Regalia',
    projectCode: '04',
    projectName: 'Woven Formations',
    year: '2024',
    location: 'Idanre, NG',
    aspectRatio: '1/1',
    widthClass: 'w-40 sm:w-48 md:w-52 lg:w-56',
    heightClass: 'h-38 sm:h-44 md:h-48 lg:h-52',
    verticalOffset: 'translate-y-3 md:translate-y-4',
    category: 'portrait',
  },
  {
    id: 'bot-7',
    filename: '7.jpg',
    src: '/assets/splash-images/7.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1000&q=85',
    title: 'Mirage of Victoria Island',
    projectCode: '01',
    projectName: 'The Silhouettes of Eko',
    year: '2025',
    location: 'Lagos, NG',
    aspectRatio: '3/4',
    widthClass: 'w-44 sm:w-52 md:w-56 lg:w-60',
    heightClass: 'h-52 sm:h-60 md:h-72 lg:h-80',
    verticalOffset: '-translate-y-1',
    category: 'fashion',
  },
  {
    id: 'bot-8',
    filename: '8.jpg',
    src: '/assets/splash-images/8.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=85',
    title: 'Velvet & Geometry',
    projectCode: '02',
    projectName: 'Indigo Resonance',
    year: '2025',
    location: 'Lagos, NG',
    aspectRatio: '2/3',
    widthClass: 'w-48 sm:w-56 md:w-64 lg:w-72',
    heightClass: 'h-62 sm:h-72 md:h-86 lg:h-[22rem]',
    verticalOffset: 'translate-y-1.5 md:translate-y-2.5',
    category: 'editorial',
  },
  {
    id: 'bot-9',
    filename: '9.jpg',
    src: '/assets/splash-images/9.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1000&q=85',
    title: 'Golden Hour at Bar Beach',
    projectCode: '01',
    projectName: 'The Silhouettes of Eko',
    year: '2024',
    location: 'Lagos, NG',
    aspectRatio: '4/3',
    widthClass: 'w-52 sm:w-60 md:w-68 lg:w-76',
    heightClass: 'h-38 sm:h-44 md:h-48 lg:h-54',
    verticalOffset: 'translate-y-2.5',
    category: 'art-direction',
  },
  {
    id: 'bot-10',
    filename: '10.jpg',
    src: '/assets/splash-images/10.jpg',
    fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1000&q=85',
    title: 'Sartorial Monolith II',
    projectCode: '04',
    projectName: 'Woven Formations',
    year: '2025',
    location: 'Akure, NG',
    aspectRatio: '4/5',
    widthClass: 'w-40 sm:w-48 md:w-56 lg:w-60',
    heightClass: 'h-52 sm:h-64 md:h-72 lg:h-80',
    verticalOffset: '-translate-y-1.5',
    category: 'fashion',
  }
];

export const SOCIAL_LINKS: SocialLink[] = [
  { id: 'instagram', label: 'INSTAGRAM', href: 'https://instagram.com' },
  { id: 'tiktok', label: 'TIKTOK', href: 'https://tiktok.com' },
  { id: 'pixieset', label: 'PIXIESET', href: 'https://pixieset.com' },
  { id: 'pinterest', label: 'PINTEREST', href: 'https://pinterest.com' },
  { id: 'whatsapp', label: 'WHATSAPP', href: 'https://whatsapp.com' },
];

export const PROJECTS_GALLERY: ProjectGallery[] = [
  {
    id: 'proj-1',
    code: '01',
    slug: '1',
    title: 'The Silhouettes of Eko',
    statement: '“A study of identity, architectural movement and quiet confidence through contemporary Nigerian high fashion.”',
    subtitle: 'High-fashion editorial across contemporary Lagos landscapes',
    year: '2025',
    location: 'Lagos, Nigeria',
    category: 'Fashion & Editorial Art Direction',
    client: 'Vogue Africa / Commissioned Spread',
    creativeDirection: 'Good Akingbade Studio',
    styling: 'Bamidele Cole',
    description: 'An exploration of architectural form, fluid draping, and modern West African identity staged against the coastal light and modernist structures of Lagos Island. Photographed on medium format analog-emulation sensor across three distinct light temperatures.',
    coverImage: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
    nextProjectSlug: '2',
    prevProjectSlug: '4',
    images: [
      {
        id: 'p1-1',
        filename: '1.1.jpg',
        src: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
        caption: 'Adunni in Ochre Silk — Marina Shoreline',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'lead-feature',
        plateNumber: 'Plate 01/06',
        subtitle: 'Natural diffused morning light over the Atlantic breakwater',
      },
      {
        id: 'p1-2',
        filename: '1.2.jpg',
        src: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
        caption: 'Sunlit Monolith in Canary Draping',
        aspectRatio: '2/3',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 02/06',
        subtitle: 'Geometric tailoring against brutalist concrete',
      },
      {
        id: 'p1-3',
        filename: '1.3.jpg',
        src: 'https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?auto=format&fit=crop&w=1400&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?auto=format&fit=crop&w=1400&q=85',
        caption: 'Saffron Draping on Reclaimed Concrete',
        aspectRatio: '16/10',
        orientation: 'landscape',
        layoutRole: 'wide-spread',
        plateNumber: 'Plate 03/06',
        subtitle: 'Panoramic perspective of raw linen in maritime wind',
      },
      {
        id: 'p1-4',
        filename: '1.4.jpg',
        src: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1200&q=85',
        caption: 'Architectural Linen study at twilight',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 04/06',
        subtitle: 'Micro-weave detail and dusk illumination',
      },
      {
        id: 'p1-5',
        filename: '1.5.jpg',
        src: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
        caption: 'Mirage of Victoria Island',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 05/06',
        subtitle: 'Low-angle study in layered organza and light refraction',
      },
      {
        id: 'p1-6',
        filename: '1.6.jpg',
        src: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1400&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1400&q=85',
        caption: 'Golden Hour at Bar Beach Archive',
        aspectRatio: '4/3',
        orientation: 'landscape',
        layoutRole: 'standalone',
        plateNumber: 'Plate 06/06',
        subtitle: 'Concluding tableau under fading coastal warmth',
      },
    ],
  },
  {
    id: 'proj-2',
    code: '02',
    slug: '2',
    title: 'Indigo Resonance',
    statement: '“Documenting the tactile richness of deep indigo pigments, ancestral shadow play, and sacred textile traditions.”',
    subtitle: 'Sacred hues and handcrafted indigo dyes of Yorubaland',
    year: '2024–2025',
    location: 'Akure, Nigeria',
    category: 'Textile Documentary & Art Direction',
    client: 'Independent Research & Arthouse Commission',
    creativeDirection: 'Good Akingbade',
    styling: 'Toluwani Ojo',
    description: 'A dedicated monograph on the organic fermentation of indigo vats, hand-resist Adire textiles, and the luminous interplay of natural sunlight piercing open-air dye compounds in southwestern Nigeria.',
    coverImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=85',
    nextProjectSlug: '3',
    prevProjectSlug: '1',
    images: [
      {
        id: 'p2-1',
        filename: '2.1.jpg',
        src: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=1200&q=85',
        caption: 'Nocturne Drapery in Deep Indigo',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'lead-feature',
        plateNumber: 'Plate 01/06',
        subtitle: 'Single-source natural backlight illuminating dyed raw cotton',
      },
      {
        id: 'p2-2',
        filename: '2.2.jpg',
        src: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1200&q=85',
        caption: 'The Gilded Veil in Natural Sunlight',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 02/06',
        subtitle: 'Sheer indigo gauze suspended over stone flooring',
      },
      {
        id: 'p2-3',
        filename: '2.3.jpg',
        src: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1200&q=85',
        caption: 'Adire Texture in Dynamic Motion',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 03/06',
        subtitle: 'High-speed shutter capturing starch-resist indigo fracture',
      },
      {
        id: 'p2-4',
        filename: '2.4.jpg',
        src: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=1200&q=85',
        caption: 'Elegance in Cobalt Studio Light',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 04/06',
        subtitle: 'Direct gaze portrait amidst drying textile reams',
      },
      {
        id: 'p2-5',
        filename: '2.5.jpg',
        src: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1200&q=85',
        caption: 'Velvet & Geometry in Indigo Shadow',
        aspectRatio: '2/3',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 05/06',
        subtitle: 'Rich tonal depth in unbleached calico and blue dye',
      },
      {
        id: 'p2-6',
        filename: '2.6.jpg',
        src: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1400&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1400&q=85',
        caption: 'Indigo Field Study — The Courtyard Vats',
        aspectRatio: '16/10',
        orientation: 'landscape',
        layoutRole: 'wide-spread',
        plateNumber: 'Plate 06/06',
        subtitle: 'Atmospheric mist and clay vats at sunrise',
      },
    ],
  },
  {
    id: 'proj-3',
    code: '03',
    slug: '3',
    title: 'Red Earth & Clay',
    statement: '“A study in permanence and warmth, pairing the dramatic geology of the Idanre granite hills with minimal haute couture.”',
    subtitle: 'Earth pigments, warm skin tones, and granite monoliths of Ondo',
    year: '2024',
    location: 'Idanre Hills & Ondo, Nigeria',
    category: 'Fine Art Landscape & Fashion',
    client: 'Arthouse Heritage / Solo Monograph',
    creativeDirection: 'Good Akingbade',
    styling: 'Folake Adeleke',
    description: 'Staged across the ancient stone stairways and red laterite soil of the historic Idanre mountain settlement. The interplay of ancient mineral textures and crisp minimalist tailoring creates a quiet, contemplative visual dialogue.',
    coverImage: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=85',
    nextProjectSlug: '4',
    prevProjectSlug: '2',
    images: [
      {
        id: 'p3-1',
        filename: '3.1.jpg',
        src: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=85',
        caption: 'Terracotta Gaze — Natural Ochre Pigment',
        aspectRatio: '1/1',
        orientation: 'square',
        layoutRole: 'lead-feature',
        plateNumber: 'Plate 01/05',
        subtitle: 'Intimate portrait illuminated by reflective red soil',
      },
      {
        id: 'p3-2',
        filename: '3.2.jpg',
        src: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=85',
        caption: 'Solitude of Idanre Granite Peak',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 02/05',
        subtitle: 'High-elevation mountain wind and dark woolen silhouette',
      },
      {
        id: 'p3-3',
        filename: '3.3.jpg',
        src: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=1200&q=85',
        caption: 'Kola Nut & Amber in Diffused Noon',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 03/05',
        subtitle: 'Warm skin tones framed against millennia-old stone',
      },
      {
        id: 'p3-4',
        filename: '3.4.jpg',
        src: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=1200&q=85',
        caption: 'Study in Bronze Light and Raw Wool',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 04/05',
        subtitle: 'Profile framing against the red cliffs of Ondo',
      },
      {
        id: 'p3-5',
        filename: '3.5.jpg',
        src: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1400&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1400&q=85',
        caption: 'The Summit Monolith — Landscape Tableau',
        aspectRatio: '16/10',
        orientation: 'landscape',
        layoutRole: 'wide-spread',
        plateNumber: 'Plate 05/05',
        subtitle: 'Expansive panorama of the sacred mountain valley',
      },
    ],
  },
  {
    id: 'proj-4',
    code: '04',
    slug: '4',
    title: 'Woven Formations',
    statement: '“Interrogating the boundary between wearable textile, ceremonial history, and sculptural volume.”',
    subtitle: 'Ceremonial weaving, contemporary silhouettes, and sculptural volume',
    year: '2025',
    location: 'Lagos & Oyo, Nigeria',
    category: 'Sculptural Fashion & Cultural Artifact',
    client: 'Design Biennial Selection / Exhibition',
    creativeDirection: 'Good Akingbade',
    styling: 'Kolawole Badmus',
    description: 'Focusing on heavy hand-loomed Aso-Oke weaves reinterpreted into contemporary geometric coats and monumental silhouettes. Each frame emphasizes the tactile tension of metallic threads, raw cotton slubs, and human grace.',
    coverImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85',
    nextProjectSlug: '1',
    prevProjectSlug: '3',
    images: [
      {
        id: 'p4-1',
        filename: '4.1.jpg',
        src: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1400&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1400&q=85',
        caption: 'Aso-Oke Motion Study in Studio A',
        aspectRatio: '4/3',
        orientation: 'landscape',
        layoutRole: 'lead-feature',
        plateNumber: 'Plate 01/06',
        subtitle: 'Dynamic flare of hand-loomed silk threads in studio lighting',
      },
      {
        id: 'p4-2',
        filename: '4.2.jpg',
        src: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=85',
        caption: 'Contemplation at Dusk in Woven Silk',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 02/06',
        subtitle: 'Subtle metallic thread reflection in low ambient light',
      },
      {
        id: 'p4-3',
        filename: '4.3.jpg',
        src: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1200&q=85',
        caption: 'Profile in Raw Umber and Stiffened Linen',
        aspectRatio: '3/4',
        orientation: 'portrait',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 03/06',
        subtitle: 'Deep contrast profile highlighting weave stiffness',
      },
      {
        id: 'p4-4',
        filename: '4.4.jpg',
        src: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1200&q=85',
        caption: 'The Elder’s Regalia — Hand-Loomed Detail',
        aspectRatio: '1/1',
        orientation: 'square',
        layoutRole: 'offset-pair',
        plateNumber: 'Plate 04/06',
        subtitle: 'Macro texture of ancestral ceremonial patterns',
      },
      {
        id: 'p4-5',
        filename: '4.5.jpg',
        src: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
        caption: 'Sartorial Monolith II — Full Silhouette',
        aspectRatio: '4/5',
        orientation: 'portrait',
        layoutRole: 'secondary-portrait',
        plateNumber: 'Plate 05/06',
        subtitle: 'Monumental cape structure standing in negative space',
      },
      {
        id: 'p4-6',
        filename: '4.6.jpg',
        src: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1400&q=85',
        fallbackSrc: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1400&q=85',
        caption: 'Woven Formations — Group Composition',
        aspectRatio: '16/10',
        orientation: 'landscape',
        layoutRole: 'wide-spread',
        plateNumber: 'Plate 06/06',
        subtitle: 'Ensemble study in structural West African textile tailoring',
      },
    ],
  },
];
